// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 39);
    pub fn classify(b: bool) -> Result<bool, runtime::CompactError> {
        Ok(!(b))
    }
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const flag: runtime::slots::CellSlot<bool> = runtime::slots::CellSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 39);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Decode this declared Cell from the borrowed public state.
        pub fn flag(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::flag.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            bool,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {}
}
