// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 47);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const open: runtime::slots::CellSlot<bool> = runtime::slots::CellSlot::new(&[0u8]);
    pub const low: runtime::slots::CounterSlot = runtime::slots::CounterSlot::new(&[1u8]);
    pub const high: runtime::slots::CounterSlot = runtime::slots::CounterSlot::new(&[2u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 47);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {
        pub fn open(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::open.witness_read(self.meter)
        }
        pub fn low(
            &self,
        ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
            let value = crate::ledger_slots::low.witness_read(self.meter)?;
            runtime::BoundedUint::<18446744073709551615>::new(value as u128)
        }
        pub fn high(
            &self,
        ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
            let value = crate::ledger_slots::high.witness_read(self.meter)?;
            runtime::BoundedUint::<18446744073709551615>::new(value as u128)
        }
    }
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Decode this declared Cell from the borrowed public state.
        pub fn open(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::open.inspect(self.state)
        }
        /// Decode this declared Counter as Compact Uint<64>.
        pub fn low(
            &self,
        ) -> Result<runtime::BoundedUint<{ u64::MAX as u128 }>, runtime::CompactError> {
            let value = crate::ledger_slots::low.inspect(self.state)?;
            Ok(
                runtime::BoundedUint::<{ u64::MAX as u128 }>::new(value as u128)
                    .expect("ledger Counter fits Uint<64>"),
            )
        }
        /// Decode this declared Counter as Compact Uint<64>.
        pub fn high(
            &self,
        ) -> Result<runtime::BoundedUint<{ u64::MAX as u128 }>, runtime::CompactError> {
            let value = crate::ledger_slots::high.inspect(self.state)?;
            Ok(
                runtime::BoundedUint::<{ u64::MAX as u128 }>::new(value as u128)
                    .expect("ledger Counter fits Uint<64>"),
            )
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {
        fn next_gate(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> (Private, bool);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
        __compact_constructor_param_0: bool,
        __compact_constructor_param_1: runtime::BoundedUint<65535>,
        __compact_constructor_param_2: runtime::BoundedUint<65535>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_cell::<bool, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
            runtime::ledger::constructor_counter(),
            runtime::ledger::constructor_counter(),
        ]);
        {
            let mut context = runtime::context::ConstructorResult::new(__compact_context, state)
                .into_circuit_context(runtime::ledger::ContractAddress::default());
            let mut total_cost = runtime::context::RunningCost::default();
            let step = context.write_cell(0, __compact_constructor_param_0)?;
            context = step.context;
            let step =
                context.increment_counter(1, __compact_constructor_param_1.value() as u16)?;
            context = step.context;
            let step =
                context.increment_counter(2, __compact_constructor_param_2.value() as u16)?;
            context = step.context;
            let _ = total_cost;
            Ok(context.into_constructor_result())
        }
    }
    pub fn checked<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: bool,
    ) -> Result<
        runtime::context::CircuitResult<Private, runtime::BoundedUint<18446744073709551615>>,
        runtime::CompactError,
    > {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 =
            runtime::BoundedUint::<255>::new(1u128).expect("Compact Uint literal fits its maximum");
        let __compact_witness_meter_1 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_1, __compact_witness_1) = witnesses.next_gate(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_1,
            }),
            __compact_argument_0,
        )?;
        total_cost += __compact_witness_meter_1.gas_cost();
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_1));
        let __compact_expression_local_2: bool = __compact_witness_1;
        if !(if if if if if __compact_param_0 {
            __compact_expression_local_2
        } else {
            false
        } {
            let __compact_query_3 = crate::ledger_slots::open.read(context)?;
            context = __compact_query_3.context;
            total_cost += __compact_query_3.gas_cost;
            __compact_query_3.result
        } else {
            false
        } {
            let __compact_argument_4 = runtime::BoundedUint::<255>::new(2u128)
                .expect("Compact Uint literal fits its maximum");
            let __compact_witness_meter_5 = runtime::context::WitnessReadMeter::new(&context);
            let (__compact_next_private_5, __compact_witness_5) = witnesses.next_gate(
                context.witness_context_with(LedgerView {
                    state: context.query.state.get_ref(),
                    meter: &__compact_witness_meter_5,
                }),
                __compact_argument_4,
            )?;
            total_cost += __compact_witness_meter_5.gas_cost();
            context.private_state = __compact_next_private_5;
            private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_5));
            __compact_witness_5
        } else {
            false
        } {
            let __compact_query_6 = crate::ledger_slots::high.read(context)?;
            context = __compact_query_6.context;
            total_cost += __compact_query_6.gas_cost;
            let __compact_expression_local_7: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_query_6.result as u128)
                    .expect("ledger Counter fits Uint<64>");
            let __compact_query_8 = crate::ledger_slots::low
                .less_than(context, (__compact_expression_local_7).value() as u64)?;
            context = __compact_query_8.context;
            total_cost += __compact_query_8.gas_cost;
            __compact_query_8.result
        } else {
            false
        } {
            let __compact_argument_9 = runtime::BoundedUint::<255>::new(3u128)
                .expect("Compact Uint literal fits its maximum");
            let __compact_witness_meter_10 = runtime::context::WitnessReadMeter::new(&context);
            let (__compact_next_private_10, __compact_witness_10) = witnesses.next_gate(
                context.witness_context_with(LedgerView {
                    state: context.query.state.get_ref(),
                    meter: &__compact_witness_meter_10,
                }),
                __compact_argument_9,
            )?;
            total_cost += __compact_witness_meter_10.gas_cost();
            context.private_state = __compact_next_private_10;
            private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_10));
            __compact_witness_10
        } else {
            false
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "nested stateful guard".to_owned(),
            ));
        }
        let __compact_query_11 = crate::ledger_slots::high.read(context)?;
        context = __compact_query_11.context;
        total_cost += __compact_query_11.gas_cost;
        let result =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_11.result as u128)
                .expect("ledger Counter fits Uint<64>");
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn unit_result<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 =
            runtime::BoundedUint::<255>::new(1u128).expect("Compact Uint literal fits its maximum");
        let __compact_witness_meter_1 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_1, __compact_witness_1) = witnesses.next_gate(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_1,
            }),
            __compact_argument_0,
        )?;
        total_cost += __compact_witness_meter_1.gas_cost();
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_1));
        let __compact_expression_local_2: bool = __compact_witness_1;
        if !(if if __compact_param_0 {
            __compact_expression_local_2
        } else {
            false
        } {
            let __compact_query_3 = crate::ledger_slots::open.read(context)?;
            context = __compact_query_3.context;
            total_cost += __compact_query_3.gas_cost;
            __compact_query_3.result
        } else {
            false
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "nested unit guard".to_owned(),
            ));
        }
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn checked<Private, W: super::TryWitnesses<Private>>(
            context: runtime::context::CircuitContext<Private>,
            witnesses: &W,
            __compact_param_0: bool,
        ) -> Result<
            runtime::recording::RecordedCircuitResult<
                Private,
                runtime::BoundedUint<18446744073709551615>,
            >,
            runtime::CompactError,
        > {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_plan_0: runtime::BoundedUint<255> =
                runtime::BoundedUint::<255>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_1: runtime::BoundedUint<255> = __compact_plan_0;
            let (frame, __compact_plan_2): (_, bool) =
                frame.try_witness_metered(|context, meter| {
                    witnesses.next_gate(
                        context.witness_context_with(super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        }),
                        __compact_plan_1,
                    )
                })?;
            let __compact_plan_3: bool = __compact_plan_2;
            let (frame, __compact_plan_5): (_, bool) = if __compact_param_0 {
                (frame, __compact_plan_3)
            } else {
                let __compact_plan_4: bool = false;
                (frame, __compact_plan_4)
            };
            let (frame, __compact_plan_8): (_, bool) = if __compact_plan_5 {
                let (frame, __compact_plan_6): (_, bool) =
                    crate::ledger_slots::open.record_read(frame)?;
                (frame, __compact_plan_6)
            } else {
                let __compact_plan_7: bool = false;
                (frame, __compact_plan_7)
            };
            let (frame, __compact_plan_13): (_, bool) = if __compact_plan_8 {
                let __compact_plan_9: runtime::BoundedUint<255> =
                    runtime::BoundedUint::<255>::new(2u128)
                        .expect("Compact Uint literal fits its maximum");
                let __compact_plan_10: runtime::BoundedUint<255> = __compact_plan_9;
                let (frame, __compact_plan_11): (_, bool) =
                    frame.try_witness_metered(|context, meter| {
                        witnesses.next_gate(
                            context.witness_context_with(super::LedgerView {
                                state: context.query.state.get_ref(),
                                meter,
                            }),
                            __compact_plan_10,
                        )
                    })?;
                (frame, __compact_plan_11)
            } else {
                let __compact_plan_12: bool = false;
                (frame, __compact_plan_12)
            };
            let (frame, __compact_plan_20): (_, bool) = if __compact_plan_13 {
                let (frame, __compact_plan_14) = crate::ledger_slots::high.record_read(frame)?;
                let __compact_plan_15: runtime::BoundedUint<18446744073709551615> =
                    runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_14 as u128)?;
                let __compact_plan_16: runtime::BoundedUint<18446744073709551615> =
                    __compact_plan_15;
                let (frame, __compact_plan_17) = crate::ledger_slots::low
                    .record_less_than(frame, (__compact_plan_16).value() as u64)?;
                let __compact_plan_18: bool = __compact_plan_17;
                (frame, __compact_plan_18)
            } else {
                let __compact_plan_19: bool = false;
                (frame, __compact_plan_19)
            };
            let (frame, __compact_plan_25): (_, bool) = if __compact_plan_20 {
                let __compact_plan_21: runtime::BoundedUint<255> =
                    runtime::BoundedUint::<255>::new(3u128)
                        .expect("Compact Uint literal fits its maximum");
                let __compact_plan_22: runtime::BoundedUint<255> = __compact_plan_21;
                let (frame, __compact_plan_23): (_, bool) =
                    frame.try_witness_metered(|context, meter| {
                        witnesses.next_gate(
                            context.witness_context_with(super::LedgerView {
                                state: context.query.state.get_ref(),
                                meter,
                            }),
                            __compact_plan_22,
                        )
                    })?;
                (frame, __compact_plan_23)
            } else {
                let __compact_plan_24: bool = false;
                (frame, __compact_plan_24)
            };
            if !__compact_plan_25 {
                return Err(runtime::CompactError::AssertionFailed(
                    "nested stateful guard".to_owned(),
                ));
            }
            let (frame, __compact_plan_26) = crate::ledger_slots::high.record_read(frame)?;
            let __compact_plan_27: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_26 as u128)?;
            Ok(frame.finish(__compact_plan_27))
        }
        pub fn unit_result<Private, W: super::TryWitnesses<Private>>(
            context: runtime::context::CircuitContext<Private>,
            witnesses: &W,
            __compact_param_0: bool,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_plan_0: runtime::BoundedUint<255> =
                runtime::BoundedUint::<255>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_1: runtime::BoundedUint<255> = __compact_plan_0;
            let (frame, __compact_plan_2): (_, bool) =
                frame.try_witness_metered(|context, meter| {
                    witnesses.next_gate(
                        context.witness_context_with(super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        }),
                        __compact_plan_1,
                    )
                })?;
            let __compact_plan_3: bool = __compact_plan_2;
            let (frame, __compact_plan_5): (_, bool) = if __compact_param_0 {
                (frame, __compact_plan_3)
            } else {
                let __compact_plan_4: bool = false;
                (frame, __compact_plan_4)
            };
            let (frame, __compact_plan_8): (_, bool) = if __compact_plan_5 {
                let (frame, __compact_plan_6): (_, bool) =
                    crate::ledger_slots::open.record_read(frame)?;
                (frame, __compact_plan_6)
            } else {
                let __compact_plan_7: bool = false;
                (frame, __compact_plan_7)
            };
            if !__compact_plan_8 {
                return Err(runtime::CompactError::AssertionFailed(
                    "nested unit guard".to_owned(),
                ));
            }
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {}
        /// A recording handle with access to the contract's witnesses.
        pub struct BorrowedContract<'a, W> {
            pub(super) witnesses: &'a W,
        }
        impl<W> BorrowedContract<'_, W> {
            pub fn checked<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                selected: bool,
            ) -> Result<
                runtime::recording::RecordedCircuitResult<
                    Private,
                    runtime::BoundedUint<18446744073709551615>,
                >,
                runtime::CompactError,
            >
            where
                W: super::TryWitnesses<Private>,
            {
                checked(context, self.witnesses, selected)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn checked_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                selected: bool,
            ) -> Result<
                runtime::transaction::RecordedCall<
                    'observed,
                    Private,
                    runtime::BoundedUint<18446744073709551615>,
                >,
                runtime::CompactError,
            >
            where
                W: super::TryWitnesses<Private>,
            {
                let input = runtime::fab::AlignedValue::from(selected);
                let recorded = self.checked(observed.circuit_context(private_state), selected)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "checked", input,
                ))
            }
            pub fn unit_result<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                selected: bool,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            where
                W: super::TryWitnesses<Private>,
            {
                unit_result(context, self.witnesses, selected)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn unit_result_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                selected: bool,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            >
            where
                W: super::TryWitnesses<Private>,
            {
                let input = runtime::fab::AlignedValue::from(selected);
                let recorded =
                    self.unit_result(observed.circuit_context(private_state), selected)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "unit_result",
                    input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn checked<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            selected: bool,
        ) -> Result<
            runtime::context::CircuitResult<Private, runtime::BoundedUint<18446744073709551615>>,
            runtime::CompactError,
        >
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::checked(context, &self.witnesses, selected)
        }
        pub fn unit_result<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            selected: bool,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::unit_result(context, &self.witnesses, selected)
        }
        /// Borrow the contract's witnesses for a replayable circuit call.
        pub fn recording(&self) -> recorded::BorrowedContract<'_, W> {
            recorded::BorrowedContract {
                witnesses: &self.witnesses,
            }
        }
    }
}
