// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use midnight_compact_runtime::*;
use std::marker::PhantomData;

midnight_compact_runtime::check_runtime_version!("0.16.100");

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell_array([Fr::default(); 2]),
            new_cell([0u8; 32]),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        let tmp = [Fr::from(0u64), Fr::from(0u64)];
        let tmp_0 = midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
            midnight_compact_runtime::AlignedValue::from(Fr::from(0u64)),
        ]);
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell_array(tmp.clone()))
            .ins(false, 1)
            .push(false, new_cell(1u8))
            .push(true, new_cell(tmp_0.clone()))
            .ins(false, 1)
            .build();

        let results = query_for_verify(&qctx, &ops, ctx.gas_limit.clone(), &ctx.cost_model)?;

        Ok(ConstructorResult {
            current_contract_state: results.context.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub(crate) fn scalar_helper(
        &self,
        ctx: CircuitContext<PS>,
        v: Fr,
    ) -> Result<CircuitResults<PS, bool>, CompactError> {
        let result = (midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(v),
        ]) == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(false)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => {
                    av
                }
                _ => {
                    return Err(CompactError::AssertionFailed(
                        "ledger: expected Read event".into(),
                    ))
                }
            };
            midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
        });
        Ok(CircuitResults {
            result,
            context: ctx,
            gas_cost: midnight_compact_runtime::RunningCost::default(),
        })
    }

    pub(crate) fn agg_helper(
        &self,
        ctx: CircuitContext<PS>,
        w: [Fr; 4],
    ) -> Result<CircuitResults<PS, bool>, CompactError> {
        let result = (midnight_compact_runtime::std_lib::persistent_hash_aligned(&{
            let __compact_hash_arg_0 = w;
            [
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[0]),
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[1]),
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[2]),
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[3]),
            ]
        }) == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(false)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => {
                    av
                }
                _ => {
                    return Err(CompactError::AssertionFailed(
                        "ledger: expected Read event".into(),
                    ))
                }
            };
            midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
        });
        Ok(CircuitResults {
            result,
            context: ctx,
            gas_cost: midnight_compact_runtime::RunningCost::default(),
        })
    }

    pub(crate) fn no_collision_helper(
        &self,
        ctx: CircuitContext<PS>,
        w: [Fr; 2],
    ) -> Result<CircuitResults<PS, bool>, CompactError> {
        let result = (midnight_compact_runtime::std_lib::persistent_hash_aligned(&{
            let __compact_hash_arg_0 = w;
            [
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[0]),
                midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[1]),
            ]
        }) == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(false)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => {
                    av
                }
                _ => {
                    return Err(CompactError::AssertionFailed(
                        "ledger: expected Read event".into(),
                    ))
                }
            };
            midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
        });
        Ok(CircuitResults {
            result,
            context: ctx,
            gas_cost: midnight_compact_runtime::RunningCost::default(),
        })
    }

    pub fn set_hash(
        &self,
        ctx: CircuitContext<PS>,
        h: [u8; 32],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(1u8))
            .push(true, new_cell(h))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn check_scalar_scope(
        &self,
        ctx: CircuitContext<PS>,
        v: [Fr; 2],
        x: Fr,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        compact_assert!(
            (midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
                midnight_compact_runtime::AlignedValue::from(x)
            ]) == {
                let _gather_ops = OpProgramGather::<DefaultDB>::new()
                    .dup(0)
                    .idx_at_index(1u8, false)
                    .popeq(false)
                    .build();
                let _gather_results = query_for_read(
                    &ctx.current_query_context,
                    &_gather_ops,
                    None,
                    &initial_cost_model(),
                )
                .map_err(|e| {
                    CompactError::AssertionFailed(format!("ledger query failed: {:?}", e))
                })?;
                let _av = match _gather_results.events.last() {
                    Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(
                        av,
                    )) => av,
                    _ => {
                        return Err(CompactError::AssertionFailed(
                            "ledger: expected Read event".into(),
                        ))
                    }
                };
                midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
            }),
            "scalar helper formal took the caller's vector type"
        );
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell_array(v))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn check_agg_scope(
        &self,
        ctx: CircuitContext<PS>,
        w: [Fr; 2],
        z: [Fr; 4],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        compact_assert!(
            (midnight_compact_runtime::std_lib::persistent_hash_aligned(&{
                let __compact_hash_arg_0 = z;
                [
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[0]),
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[1]),
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[2]),
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[3]),
                ]
            }) == {
                let _gather_ops = OpProgramGather::<DefaultDB>::new()
                    .dup(0)
                    .idx_at_index(1u8, false)
                    .popeq(false)
                    .build();
                let _gather_results = query_for_read(
                    &ctx.current_query_context,
                    &_gather_ops,
                    None,
                    &initial_cost_model(),
                )
                .map_err(|e| {
                    CompactError::AssertionFailed(format!("ledger query failed: {:?}", e))
                })?;
                let _av = match _gather_results.events.last() {
                    Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(
                        av,
                    )) => av,
                    _ => {
                        return Err(CompactError::AssertionFailed(
                            "ledger: expected Read event".into(),
                        ))
                    }
                };
                midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
            }),
            "aggregate helper formal took the caller's shorter vector type"
        );
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell_array(w))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn check_no_collision_scope(
        &self,
        ctx: CircuitContext<PS>,
        v: [Fr; 2],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        compact_assert!(
            (midnight_compact_runtime::std_lib::persistent_hash_aligned(&{
                let __compact_hash_arg_0 = v;
                [
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[0]),
                    midnight_compact_runtime::AlignedValue::from(__compact_hash_arg_0[1]),
                ]
            }) == {
                let _gather_ops = OpProgramGather::<DefaultDB>::new()
                    .dup(0)
                    .idx_at_index(1u8, false)
                    .popeq(false)
                    .build();
                let _gather_results = query_for_read(
                    &ctx.current_query_context,
                    &_gather_ops,
                    None,
                    &initial_cost_model(),
                )
                .map_err(|e| {
                    CompactError::AssertionFailed(format!("ledger query failed: {:?}", e))
                })?;
                let _av = match _gather_results.events.last() {
                    Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(
                        av,
                    )) => av,
                    _ => {
                        return Err(CompactError::AssertionFailed(
                            "ledger: expected Read event".into(),
                        ))
                    }
                };
                midnight_compact_runtime::std_lib::decode_bytes::<32>(_av)?
            }),
            "aggregate helper formal was not recovered"
        );
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell_array(v))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn field_vec(&self) -> Result<[Fr; 2], CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_vector_fr::<2>(av)
    }
    pub fn hash_cell(&self) -> Result<[u8; 32], CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_bytes::<32>(av)
    }
}

pub mod pure_circuits {}
