// Generated by compactc. Do not edit.

pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct Pair {
        pub amount: runtime::Field,
        pub active: bool,
    }
}
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 1);
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 1);
    pub fn initial_state<Private>(
        context: runtime::context::ConstructorContext<Private>,
    ) -> runtime::context::ConstructorResult<Private> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            crate::types::Pair,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        runtime::context::ConstructorResult::new(context, state)
    }
}
