// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
}
/// Typed descriptors for Compact Cell and Counter declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const doubled: runtime::slots::CellSlot<
        runtime::FixedVector<runtime::BoundedUint<18446744073709551615>, 3>,
    > = runtime::slots::CellSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            runtime::FixedVector<runtime::BoundedUint<18446744073709551615>, 3>,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        {
            let mut context = runtime::context::ConstructorResult::new(__compact_context, state)
                .into_circuit_context(runtime::ledger::ContractAddress::default());
            let mut total_cost = runtime::context::RunningCost::default();
            let __compact_constructor_local_0: runtime::FixedVector<
                runtime::BoundedUint<18446744073709551615>,
                3,
            > = {
                let __compact_map_source = {
                    let __compact_cast_source_0 = (
                        runtime::BoundedUint::<18446744073709551615>::new(1u128)
                            .expect("Compact Uint literal fits its maximum"),
                        runtime::BoundedUint::<2>::new(2u128)
                            .expect("Compact Uint literal fits its maximum"),
                        runtime::BoundedUint::<3>::new(3u128)
                            .expect("Compact Uint literal fits its maximum"),
                    );
                    let (__compact_cast_item_0_0, __compact_cast_item_0_1, __compact_cast_item_0_2) =
                        __compact_cast_source_0;
                    runtime::FixedVector::new([
                        __compact_cast_item_0_0,
                        runtime::cast_unsigned::<2, 18446744073709551615>(__compact_cast_item_0_1)?,
                        runtime::cast_unsigned::<3, 18446744073709551615>(__compact_cast_item_0_2)?,
                    ])
                };
                let mut __compact_mapped = Vec::with_capacity(3);
                for x in __compact_map_source.into_array() {
                    __compact_mapped.push(runtime::cast_unsigned::<
                        36893488147419103231,
                        18446744073709551615,
                    >(runtime::multiply_unsigned::<
                        36893488147419103230,
                        36893488147419103230,
                        36893488147419103231,
                    >(
                        runtime::cast_unsigned::<18446744073709551615, 36893488147419103230>(x)?,
                        runtime::BoundedUint::<36893488147419103230>::new(2u128)
                            .expect("Compact Uint literal fits its maximum"),
                    )?)?);
                }
                runtime::FixedVector::new(
                    __compact_mapped
                        .try_into()
                        .expect("Vector map preserves its length"),
                )
            };
            let step = context.write_cell(0, (__compact_constructor_local_0.clone()).clone())?;
            context = step.context;
            let _ = total_cost;
            Ok(context.into_constructor_result())
        }
    }
    pub fn ping<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::FixedVector<
            runtime::BoundedUint<18446744073709551615>,
            3,
        > = {
            let __compact_map_source = {
                let __compact_cast_source_0 = (
                    runtime::BoundedUint::<18446744073709551615>::new(0u128)
                        .expect("Compact Uint literal fits its maximum"),
                    runtime::BoundedUint::<0>::new(0u128)
                        .expect("Compact Uint literal fits its maximum"),
                    runtime::BoundedUint::<0>::new(0u128)
                        .expect("Compact Uint literal fits its maximum"),
                );
                let (__compact_cast_item_0_0, __compact_cast_item_0_1, __compact_cast_item_0_2) =
                    __compact_cast_source_0;
                runtime::FixedVector::new([
                    __compact_cast_item_0_0,
                    runtime::cast_unsigned::<0, 18446744073709551615>(__compact_cast_item_0_1)?,
                    runtime::cast_unsigned::<0, 18446744073709551615>(__compact_cast_item_0_2)?,
                ])
            };
            let mut __compact_mapped = Vec::with_capacity(3);
            for x in __compact_map_source.into_array() {
                __compact_mapped.push(x);
            }
            runtime::FixedVector::new(
                __compact_mapped
                    .try_into()
                    .expect("Vector map preserves its length"),
            )
        };
        let step = context.write_cell(0, __compact_action_local_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {
        pub fn ping<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::ping(context)
        }
    }
}
