// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 18);
    pub fn hash_field(
        value: runtime::Field,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::keccak256(value))
    }
    pub fn hash_bytes(
        value: runtime::FixedBytes<4>,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::keccak256(value))
    }
    pub fn hash_pair(
        value: runtime::FixedVector<runtime::Field, 2>,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::keccak256(value.clone()))
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 18);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {
        fn echo(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::Field,
        ) -> (Private, runtime::Field);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn hash_echo<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<
        runtime::context::CircuitResult<Private, runtime::FixedBytes<32>>,
        runtime::CompactError,
    > {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let __compact_witness_meter_1 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_1, __compact_witness_1) = witnesses.echo(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_1,
            }),
            __compact_argument_0,
        )?;
        total_cost += __compact_witness_meter_1.gas_cost();
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = runtime::keccak256(__compact_witness_1);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {
        pub fn hash_echo<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::Field,
        ) -> Result<
            runtime::context::CircuitResult<Private, runtime::FixedBytes<32>>,
            runtime::CompactError,
        >
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::hash_echo(context, &self.witnesses, __compact_param_0)
        }
    }
}
