// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 46);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const names: runtime::slots::SetSlot<runtime::OpaqueString> =
        runtime::slots::SetSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 46);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Inspect this declared Set in the borrowed public state.
        pub fn names(
            &self,
        ) -> Result<runtime::ledger::SetView<'a, runtime::OpaqueString, D>, runtime::CompactError>
        {
            crate::ledger_slots::names.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_set()]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn addName<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::OpaqueString,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::names.insert(context, __compact_param_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn hasName<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::OpaqueString,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = crate::ledger_slots::names.member(context, __compact_param_0.clone())?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn addName<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::OpaqueString,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame =
                crate::ledger_slots::names.record_insert(frame, (__compact_param_0).clone())?;
            Ok(frame.finish(()))
        }
        pub fn hasName<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::OpaqueString,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, bool>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_recorded_key_0 = (__compact_param_0).clone();
            let (frame, __compact_recorded_member_1): (_, bool) =
                crate::ledger_slots::names.record_member(frame, __compact_recorded_key_0)?;
            Ok(frame.finish(__compact_recorded_member_1))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn addName<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                name: runtime::OpaqueString,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::addName(context, name)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn addName_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                name: runtime::OpaqueString,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from((name).clone());
                let recorded = self.addName(observed.circuit_context(private_state), name)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "addName", input,
                ))
            }
            pub fn hasName<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                name: runtime::OpaqueString,
            ) -> Result<
                runtime::recording::RecordedCircuitResult<Private, bool>,
                runtime::CompactError,
            > {
                crate::ledger_contract::recorded::hasName(context, name)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn hasName_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                name: runtime::OpaqueString,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, bool>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from((name).clone());
                let recorded = self.hasName(observed.circuit_context(private_state), name)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "hasName", input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn addName<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            name: runtime::OpaqueString,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::addName(context, name)
        }
        pub fn hasName<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            name: runtime::OpaqueString,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
            crate::ledger_contract::hasName(context, name)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
