// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 35);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const flag: runtime::slots::CellSlot<bool> = runtime::slots::CellSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 35);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {
        pub fn flag(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::flag.witness_read(self.meter)
        }
    }
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Decode this declared Cell from the borrowed public state.
        pub fn flag(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::flag.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {
        fn read_flag(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, bool);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            bool,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn set_flag<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::flag.write(context, true)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn private_check<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.read_flag(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_0));
        let result = __compact_witness_0;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn set_flag<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::flag.record_write(frame, true)?;
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn set_flag<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::set_flag(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn set_flag_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded = self.set_flag(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "set_flag", input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn set_flag<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::set_flag(context)
        }
        pub fn private_check<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::private_check(context, &self.witnesses)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
