// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {
        fn secret_point(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::Field,
        ) -> (Private, runtime::JubjubPoint);
        fn secret_scalar(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::Field,
        ) -> (Private, runtime::Field);
    }
    pub fn initial_state<Private>(
        context: runtime::context::ConstructorContext<Private>,
    ) -> runtime::context::ConstructorResult<Private> {
        let state = runtime::ledger::contract_state(vec![]);
        runtime::context::ConstructorResult::new(context, state)
    }
    pub fn combine<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let __compact_value_2 = __compact_witness_1;
        let __compact_argument_3 = __compact_param_0;
        let (__compact_next_private_4, __compact_witness_4) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_3,
        );
        context.private_state = __compact_next_private_4;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_4.clone(),
        ));
        let result = runtime::ec_add(__compact_value_2, __compact_witness_4);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn scale<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let __compact_value_2 = __compact_witness_1;
        let __compact_argument_3 = __compact_param_0;
        let (__compact_next_private_4, __compact_witness_4) = witnesses.secret_scalar(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_3,
        );
        context.private_state = __compact_next_private_4;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_4.clone(),
        ));
        let result = runtime::ec_mul(__compact_value_2, __compact_witness_4)?;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn point_x<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::Field>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = runtime::jubjub_point_x(__compact_witness_1);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn point_y<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::Field>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = runtime::jubjub_point_y(__compact_witness_1);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn negate<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = runtime::ec_neg(__compact_witness_1);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn reveal<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_point(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = __compact_witness_1;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn hash_scalar<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_scalar(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result = runtime::hash_to_curve(__compact_witness_1);
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn generator<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::JubjubPoint>, runtime::CompactError>
    {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.secret_scalar(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let result =
            runtime::ec_mul_generator(runtime::jubjub_scalar_from_native(__compact_witness_1))?;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
