// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 2);
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 2);
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        context: runtime::context::ConstructorContext<Private>,
    ) -> runtime::context::ConstructorResult<Private> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            bool,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        runtime::context::ConstructorResult::new(context, state)
    }
    pub fn set_flag<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.write_cell(0, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        Ok(runtime::context::CircuitResult {
            context,
            result: (),
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
