// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 50);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const controller: runtime::slots::CellSlot<runtime::JubjubPoint> =
        runtime::slots::CellSlot::new(&[0u8]);
    pub const recovery: runtime::slots::CellSlot<runtime::JubjubPoint> =
        runtime::slots::CellSlot::new(&[1u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 50);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Decode this declared Cell from the borrowed public state.
        pub fn controller(&self) -> Result<runtime::JubjubPoint, runtime::CompactError> {
            crate::ledger_slots::controller.inspect(self.state)
        }
        /// Decode this declared Cell from the borrowed public state.
        pub fn recovery(&self) -> Result<runtime::JubjubPoint, runtime::CompactError> {
            crate::ledger_slots::recovery.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
        __compact_constructor_param_0: runtime::JubjubPoint,
        __compact_constructor_param_1: runtime::JubjubPoint,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let __compact_constructor_value_0 = __compact_constructor_param_0;
        let __compact_constructor_value_1 = __compact_constructor_param_1;
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_cell::<runtime::JubjubPoint, runtime::ledger::DefaultDB>(
                __compact_constructor_value_0,
            ),
            runtime::ledger::constructor_cell::<runtime::JubjubPoint, runtime::ledger::DefaultDB>(
                __compact_constructor_value_1,
            ),
        ]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub(crate) fn changes<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::JubjubPoint,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_value_0 = runtime::jubjub_point_x(__compact_param_0);
        let __compact_query_1 = crate::ledger_slots::controller.read(context)?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        if !(if __compact_value_0 != runtime::jubjub_point_x(__compact_query_1.result) {
            true
        } else {
            let __compact_value_2 = runtime::jubjub_point_y(__compact_param_0);
            let __compact_query_3 = crate::ledger_slots::controller.read(context)?;
            context = __compact_query_3.context;
            total_cost += __compact_query_3.gas_cost;
            __compact_value_2 != runtime::jubjub_point_y(__compact_query_3.result)
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "same controller".to_owned(),
            ));
        }
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub(crate) fn distinct<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::JubjubPoint,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_value_0 = runtime::jubjub_point_x(__compact_param_0);
        let __compact_query_1 = crate::ledger_slots::recovery.read(context)?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        if !(if __compact_value_0 != runtime::jubjub_point_x(__compact_query_1.result) {
            true
        } else {
            let __compact_value_2 = runtime::jubjub_point_y(__compact_param_0);
            let __compact_query_3 = crate::ledger_slots::recovery.read(context)?;
            context = __compact_query_3.context;
            total_cost += __compact_query_3.gas_cost;
            __compact_value_2 != runtime::jubjub_point_y(__compact_query_3.result)
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "same recovery".to_owned(),
            ));
        }
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn check<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::JubjubPoint,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::JubjubPoint = __compact_param_0;
        let __compact_call_argument_0 = __compact_action_local_0;
        let call_step = changes(context, __compact_call_argument_0)?;
        let context = call_step.context;
        total_cost += call_step.gas_cost;
        let __compact_call_argument_1 = __compact_action_local_0;
        let call_step = distinct(context, __compact_call_argument_1)?;
        let context = call_step.context;
        total_cost += call_step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn check<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::JubjubPoint,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_plan_0: runtime::JubjubPoint = __compact_param_0;
            let __compact_plan_1: runtime::JubjubPoint = __compact_plan_0;
            let __compact_plan_2: runtime::Field = runtime::jubjub_point_x(__compact_plan_1);
            let (frame, __compact_plan_3): (_, runtime::JubjubPoint) =
                crate::ledger_slots::controller.record_read(frame)?;
            let __compact_plan_4: runtime::Field = runtime::jubjub_point_x(__compact_plan_3);
            let __compact_plan_5: bool = __compact_plan_2 != __compact_plan_4;
            let (frame, __compact_plan_11): (_, bool) = if __compact_plan_5 {
                let __compact_plan_6: bool = true;
                (frame, __compact_plan_6)
            } else {
                let __compact_plan_7: runtime::Field = runtime::jubjub_point_y(__compact_plan_1);
                let (frame, __compact_plan_8): (_, runtime::JubjubPoint) =
                    crate::ledger_slots::controller.record_read(frame)?;
                let __compact_plan_9: runtime::Field = runtime::jubjub_point_y(__compact_plan_8);
                let __compact_plan_10: bool = __compact_plan_7 != __compact_plan_9;
                (frame, __compact_plan_10)
            };
            if !__compact_plan_11 {
                return Err(runtime::CompactError::AssertionFailed(
                    "same controller".to_owned(),
                ));
            }
            let __compact_plan_12: runtime::JubjubPoint = __compact_plan_0;
            let __compact_plan_13: runtime::Field = runtime::jubjub_point_x(__compact_plan_12);
            let (frame, __compact_plan_14): (_, runtime::JubjubPoint) =
                crate::ledger_slots::recovery.record_read(frame)?;
            let __compact_plan_15: runtime::Field = runtime::jubjub_point_x(__compact_plan_14);
            let __compact_plan_16: bool = __compact_plan_13 != __compact_plan_15;
            let (frame, __compact_plan_22): (_, bool) = if __compact_plan_16 {
                let __compact_plan_17: bool = true;
                (frame, __compact_plan_17)
            } else {
                let __compact_plan_18: runtime::Field = runtime::jubjub_point_y(__compact_plan_12);
                let (frame, __compact_plan_19): (_, runtime::JubjubPoint) =
                    crate::ledger_slots::recovery.record_read(frame)?;
                let __compact_plan_20: runtime::Field = runtime::jubjub_point_y(__compact_plan_19);
                let __compact_plan_21: bool = __compact_plan_18 != __compact_plan_20;
                (frame, __compact_plan_21)
            };
            if !__compact_plan_22 {
                return Err(runtime::CompactError::AssertionFailed(
                    "same recovery".to_owned(),
                ));
            }
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn check<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                value: runtime::JubjubPoint,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::check(context, value)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn check_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                value: runtime::JubjubPoint,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(value);
                let recorded = self.check(observed.circuit_context(private_state), value)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "check", input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn check<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            value: runtime::JubjubPoint,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::check(context, value)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
