// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![new_historic_merkle_tree(3)]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, compact_runtime::ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn add_default(
        &self,
        ctx: CircuitContext<PS>,
        idx: u64,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .idx_at_index(0u8, true)
            .push(false, new_cell(idx))
            .push(
                true,
                new_cell(leaf_hash(&ValueReprAlignedValue(AlignedValue::from(0u8)))),
            )
            .ins(false, 2)
            .idx_at_index(1u8, true)
            .push(false, new_cell(idx))
            .addi(1)
            .dup(1)
            .dup(1)
            .lt()
            .branch(2)
            .pop()
            .jmp(2)
            .swap(0)
            .pop()
            .ins(false, 1)
            .idx_at_index(2u8, true)
            .dup(2)
            .idx_at_index(0u8, false)
            .root()
            .push(true, StateValue::Null)
            .ins(false, 1)
            .ins(true, 2)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {}

pub mod pure_circuits {}
