// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct LeafPreimage {
        pub domain_sep: runtime::FixedBytes<6>,
        pub data: crate::types::commitment,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerkleTreeDigest,
    )]
    pub struct MerkleTreeDigest {
        pub field: runtime::Field,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerklePath,
    )]
    pub struct MerkleTreePath {
        pub leaf: crate::types::commitment,
        pub path: runtime::FixedVector<crate::types::MerkleTreePathEntry, 32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerklePathEntry,
    )]
    pub struct MerkleTreePathEntry {
        pub sibling: crate::types::MerkleTreeDigest,
        pub goes_left: bool,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct Nonce {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct coin_info {
        pub nonce: crate::types::Nonce,
        pub opening: crate::types::opening,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct commitment {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct nullifier {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct opening {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct public_key {
        pub zk: crate::types::zk_public_key,
        pub encryption: runtime::OpaqueBytes,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct zk_public_key {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct zk_secret_key {
        pub bytes: runtime::FixedBytes<32>,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 46);
    pub(crate) fn merkleTreePathRoot(
        path: crate::types::MerkleTreePath,
    ) -> Result<crate::types::MerkleTreeDigest, runtime::CompactError> {
        Ok(crate::types::MerkleTreeDigest {
            field: {
                let __compact_fold_source = ((path.clone()).path).clone();
                let mut __compact_fold_accumulator = runtime::degrade_to_transient(
                    runtime::persistent_hash(crate::types::LeafPreimage {
                        domain_sep: runtime::FixedBytes::new([
                            109u8, 100u8, 110u8, 58u8, 108u8, 104u8,
                        ]),
                        data: ((path.clone()).leaf).clone(),
                    }),
                );
                for __compact_fold_item in __compact_fold_source.into_array() {
                    __compact_fold_accumulator = crate::pure_circuits::merkleTreePathEntryRoot(
                        __compact_fold_accumulator,
                        __compact_fold_item,
                    )?;
                }
                __compact_fold_accumulator
            },
        })
    }
    pub(crate) fn merkleTreePathEntryRoot(
        recursiveDigest: runtime::Field,
        entry: crate::types::MerkleTreePathEntry,
    ) -> Result<runtime::Field, runtime::CompactError> {
        Ok({
            let __compact_local_left: runtime::Field = if (entry.clone()).goes_left {
                recursiveDigest
            } else {
                (((entry.clone()).sibling).clone()).field
            };
            {
                let __compact_local_right: runtime::Field = if (entry.clone()).goes_left {
                    (((entry.clone()).sibling).clone()).field
                } else {
                    recursiveDigest
                };
                runtime::transient_hash((__compact_local_left, __compact_local_right))
            }
        })
    }
    pub(crate) fn derive_nullifier(
        coin: crate::types::coin_info,
        sk: crate::types::zk_secret_key,
    ) -> Result<crate::types::nullifier, runtime::CompactError> {
        Ok(crate::types::nullifier {
            bytes: runtime::persistent_hash((
                runtime::FixedBytes::new([
                    108u8, 97u8, 114u8, 101u8, 115u8, 58u8, 122u8, 101u8, 114u8, 111u8, 99u8, 97u8,
                    115u8, 104u8, 58u8, 99u8, 111u8, 109u8, 109u8, 105u8, 116u8, 0u8, 0u8, 0u8,
                    0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                ]),
                (((coin.clone()).nonce).clone()).bytes,
                (((coin.clone()).opening).clone()).bytes,
                (sk.clone()).bytes,
            )),
        })
    }
    pub(crate) fn derive_zk_public_key(
        sk: crate::types::zk_secret_key,
    ) -> Result<crate::types::zk_public_key, runtime::CompactError> {
        Ok(crate::types::zk_public_key {
            bytes: runtime::persistent_hash((sk.clone()).bytes),
        })
    }
    pub(crate) fn commitment_from_coin_info(
        coin: crate::types::coin_info,
        pk: crate::types::zk_public_key,
    ) -> Result<crate::types::commitment, runtime::CompactError> {
        Ok(crate::types::commitment {
            bytes: runtime::persistent_hash((
                runtime::FixedBytes::new([
                    108u8, 97u8, 114u8, 101u8, 115u8, 58u8, 122u8, 101u8, 114u8, 111u8, 99u8, 97u8,
                    115u8, 104u8, 58u8, 99u8, 111u8, 109u8, 109u8, 105u8, 116u8, 0u8, 0u8, 0u8,
                    0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                ]),
                (((coin.clone()).nonce).clone()).bytes,
                (((coin.clone()).opening).clone()).bytes,
                (pk.clone()).bytes,
            )),
        })
    }
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const nullifiers: runtime::slots::SetSlot<crate::types::nullifier> =
        runtime::slots::SetSlot::new(&[0u8]);
    pub const commitments: runtime::slots::MerkleSlot<crate::types::commitment, 32u8, true> =
        runtime::slots::MerkleSlot::new(&[1u8]);
    pub const ciphertexts: runtime::slots::CellSlot<runtime::OpaqueBytes> =
        runtime::slots::CellSlot::new(&[2u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 46);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {
        pub fn nullifiers(
            &self,
        ) -> Result<
            runtime::ledger::MeteredSetView<
                'a,
                crate::types::nullifier,
                runtime::ledger::DefaultDB,
            >,
            runtime::CompactError,
        > {
            crate::ledger_slots::nullifiers.witness_view(self.meter)
        }
        pub fn commitments(
            &self,
        ) -> Result<
            runtime::ledger::MeteredHistoricMerkleTreeView<
                'a,
                crate::types::MerkleTreeDigest,
                runtime::ledger::DefaultDB,
            >,
            runtime::CompactError,
        > {
            crate::ledger_slots::commitments.witness_view(self.meter)
        }
        pub fn ciphertexts(&self) -> Result<runtime::OpaqueBytes, runtime::CompactError> {
            crate::ledger_slots::ciphertexts.witness_read(self.meter)
        }
    }
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Inspect this declared Set in the borrowed public state.
        pub fn nullifiers(
            &self,
        ) -> Result<runtime::ledger::SetView<'a, crate::types::nullifier, D>, runtime::CompactError>
        {
            crate::ledger_slots::nullifiers.inspect(self.state)
        }
        /// Inspect this declared historic Merkle tree in the borrowed public state.
        pub fn commitments(
            &self,
        ) -> Result<
            runtime::slots::HistoricMerkleStateView<'a, crate::types::commitment, 32u8, D>,
            runtime::CompactError,
        > {
            crate::ledger_slots::commitments.inspect(self.state)
        }
        /// Decode this declared Cell from the borrowed public state.
        pub fn ciphertexts(&self) -> Result<runtime::OpaqueBytes, runtime::CompactError> {
            crate::ledger_slots::ciphertexts.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {
        fn private_zk_secret_key(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, crate::types::zk_secret_key);
        fn private_remove_coin(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: crate::types::coin_info,
        ) -> (Private, ());
        fn private_zk_public_key(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, crate::types::zk_public_key);
        fn private_add_coin(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: crate::types::coin_info,
        ) -> (Private, ());
        fn context_path_of(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: crate::types::commitment,
        ) -> (Private, crate::types::MerkleTreePath);
        fn context_new_coin_info(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, crate::types::coin_info);
        fn context_encrypt(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::OpaqueBytes,
            __compact_param_1: crate::types::coin_info,
        ) -> (Private, runtime::OpaqueBytes);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_set(),
            runtime::ledger::constructor_historic_merkle_tree(32u8),
            runtime::ledger::constructor_cell::<runtime::OpaqueBytes, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
        ]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn spend<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: crate::types::public_key,
        __compact_param_1: crate::types::coin_info,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.private_zk_secret_key(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_0).clone(),
        ));
        let __compact_action_local_0: crate::types::zk_secret_key = __compact_witness_0;
        let __compact_call_argument_1 = __compact_param_1.clone();
        let __compact_call_argument_2 = __compact_action_local_0.clone();
        let __compact_action_local_1: crate::types::nullifier =
            crate::pure_circuits::derive_nullifier(
                __compact_call_argument_1,
                __compact_call_argument_2,
            )?;
        let mut context = context;
        let __compact_query_3 = crate::ledger_slots::nullifiers
            .member(context, (__compact_action_local_1.clone()).clone())?;
        context = __compact_query_3.context;
        total_cost += __compact_query_3.gas_cost;
        if __compact_query_3.result {
            return Err(runtime::CompactError::AssertionFailed(
                "spend: Coin already spent".to_owned(),
            ));
        }
        let step =
            crate::ledger_slots::nullifiers.insert(context, __compact_action_local_1.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let __compact_call_argument_4 = __compact_action_local_0.clone();
        let __compact_action_local_2: crate::types::zk_public_key =
            crate::pure_circuits::derive_zk_public_key(__compact_call_argument_4)?;
        let __compact_call_argument_5 = __compact_param_1.clone();
        let __compact_call_argument_6 = __compact_action_local_2.clone();
        let __compact_action_local_3: crate::types::commitment =
            crate::pure_circuits::commitment_from_coin_info(
                __compact_call_argument_5,
                __compact_call_argument_6,
            )?;
        let mut context = context;
        let __compact_argument_7 = __compact_action_local_3.clone();
        let __compact_witness_meter_8 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_8, __compact_witness_8) = witnesses.context_path_of(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_8,
            }),
            __compact_argument_7,
        )?;
        total_cost += __compact_witness_meter_8.gas_cost();
        context.private_state = __compact_next_private_8;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_8).clone(),
        ));
        let __compact_action_local_4: crate::types::MerkleTreePath = __compact_witness_8;
        let mut context = context;
        let __compact_call_argument_9 = __compact_action_local_4.clone();
        let __compact_expression_local_10: crate::types::MerkleTreeDigest =
            crate::pure_circuits::merkleTreePathRoot(__compact_call_argument_9)?;
        let __compact_query_11 = crate::ledger_slots::commitments
            .check_root(context, __compact_expression_local_10.clone())?;
        context = __compact_query_11.context;
        total_cost += __compact_query_11.gas_cost;
        if !(if __compact_query_11.result {
            let __compact_value_12 = __compact_action_local_3.clone();
            __compact_value_12 == ((__compact_action_local_4.clone()).leaf).clone()
        } else {
            false
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "spend: Illegal state: merkle path not recognized by public state".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_witness_meter_13 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_13, __compact_witness_13) =
            witnesses.context_new_coin_info(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_13,
            }))?;
        total_cost += __compact_witness_meter_13.gas_cost();
        context.private_state = __compact_next_private_13;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_13).clone(),
        ));
        let __compact_action_local_5: crate::types::coin_info = __compact_witness_13;
        let __compact_call_argument_14 = __compact_action_local_5.clone();
        let __compact_call_argument_15 = ((__compact_param_0.clone()).zk).clone();
        let __compact_action_local_6: crate::types::commitment =
            crate::pure_circuits::commitment_from_coin_info(
                __compact_call_argument_14,
                __compact_call_argument_15,
            )?;
        let step =
            crate::ledger_slots::commitments.insert(context, __compact_action_local_6.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_argument_16 = ((__compact_param_0.clone()).encryption).clone();
        let __compact_argument_17 = __compact_action_local_5.clone();
        let __compact_witness_meter_18 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_18, __compact_witness_18) = witnesses.context_encrypt(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_18,
            }),
            __compact_argument_16,
            __compact_argument_17,
        )?;
        total_cost += __compact_witness_meter_18.gas_cost();
        context.private_state = __compact_next_private_18;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_18).clone(),
        ));
        let __compact_action_local_7: runtime::OpaqueBytes = __compact_witness_18;
        let step =
            crate::ledger_slots::ciphertexts.write(context, __compact_action_local_7.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_argument_19 = __compact_param_1.clone();
        let __compact_witness_meter_20 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_20, __compact_witness_20) = witnesses.private_remove_coin(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_20,
            }),
            __compact_argument_19,
        )?;
        total_cost += __compact_witness_meter_20.gas_cost();
        context.private_state = __compact_next_private_20;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_20));
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn zerocash_mint<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.context_new_coin_info(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_0).clone(),
        ));
        let __compact_action_local_0: crate::types::coin_info = __compact_witness_0;
        let mut context = context;
        let __compact_witness_meter_1 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_1, __compact_witness_1) =
            witnesses.private_zk_public_key(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_1,
            }))?;
        total_cost += __compact_witness_meter_1.gas_cost();
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            (__compact_witness_1).clone(),
        ));
        let __compact_action_local_1: crate::types::zk_public_key = __compact_witness_1;
        let mut context = context;
        let __compact_argument_2 = __compact_action_local_0.clone();
        let __compact_witness_meter_3 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_3, __compact_witness_3) = witnesses.private_add_coin(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_3,
            }),
            __compact_argument_2,
        )?;
        total_cost += __compact_witness_meter_3.gas_cost();
        context.private_state = __compact_next_private_3;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(__compact_witness_3));
        let __compact_call_argument_4 = __compact_action_local_0.clone();
        let __compact_call_argument_5 = __compact_action_local_1.clone();
        let __compact_action_local_2: crate::types::commitment =
            crate::pure_circuits::commitment_from_coin_info(
                __compact_call_argument_4,
                __compact_call_argument_5,
            )?;
        let step =
            crate::ledger_slots::commitments.insert(context, __compact_action_local_2.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn spend<Private, W: super::TryWitnesses<Private>>(
            context: runtime::context::CircuitContext<Private>,
            witnesses: &W,
            __compact_param_0: crate::types::public_key,
            __compact_param_1: crate::types::coin_info,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let (frame, __compact_plan_0): (_, crate::types::zk_secret_key) = frame
                .try_witness_metered(|context, meter| {
                    witnesses.private_zk_secret_key(context.witness_context_with(
                        super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        },
                    ))
                })?;
            let __compact_plan_1: crate::types::zk_secret_key = __compact_plan_0;
            let __compact_plan_2: crate::types::coin_info = (__compact_param_1).clone();
            let __compact_plan_3: crate::types::zk_secret_key = (__compact_plan_1).clone();
            let __compact_plan_4: crate::types::nullifier =
                crate::pure_circuits::derive_nullifier(__compact_plan_2, __compact_plan_3)?;
            let __compact_plan_5: crate::types::nullifier = __compact_plan_4;
            let (frame, __compact_plan_6): (_, bool) =
                crate::ledger_slots::nullifiers.record_member(frame, (__compact_plan_5).clone())?;
            let (frame, __compact_plan_9): (_, bool) = if __compact_plan_6 {
                let __compact_plan_7: bool = false;
                (frame, __compact_plan_7)
            } else {
                let __compact_plan_8: bool = true;
                (frame, __compact_plan_8)
            };
            if !__compact_plan_9 {
                return Err(runtime::CompactError::AssertionFailed(
                    "spend: Coin already spent".to_owned(),
                ));
            }
            let frame =
                crate::ledger_slots::nullifiers.record_insert(frame, (__compact_plan_5).clone())?;
            let __compact_plan_10: crate::types::zk_secret_key = (__compact_plan_1).clone();
            let __compact_plan_11: crate::types::zk_public_key =
                crate::pure_circuits::derive_zk_public_key(__compact_plan_10)?;
            let __compact_plan_12: crate::types::zk_public_key = __compact_plan_11;
            let __compact_plan_13: crate::types::coin_info = (__compact_param_1).clone();
            let __compact_plan_14: crate::types::zk_public_key = (__compact_plan_12).clone();
            let __compact_plan_15: crate::types::commitment =
                crate::pure_circuits::commitment_from_coin_info(
                    __compact_plan_13,
                    __compact_plan_14,
                )?;
            let __compact_plan_16: crate::types::commitment = __compact_plan_15;
            let __compact_plan_17: crate::types::commitment = (__compact_plan_16).clone();
            let (frame, __compact_plan_18): (_, crate::types::MerkleTreePath) = frame
                .try_witness_metered(|context, meter| {
                    witnesses.context_path_of(
                        context.witness_context_with(super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        }),
                        __compact_plan_17,
                    )
                })?;
            let __compact_plan_19: crate::types::MerkleTreePath = __compact_plan_18;
            let __compact_plan_20: crate::types::MerkleTreePath = (__compact_plan_19).clone();
            let __compact_plan_21: crate::types::MerkleTreeDigest =
                crate::pure_circuits::merkleTreePathRoot(__compact_plan_20)?;
            let __compact_plan_22: crate::types::MerkleTreeDigest = __compact_plan_21;
            let (frame, __compact_plan_23): (_, bool) = crate::ledger_slots::commitments
                .record_check_root(frame, (__compact_plan_22).clone())?;
            let (frame, __compact_plan_27): (_, bool) = if __compact_plan_23 {
                let __compact_plan_24: crate::types::commitment =
                    (((__compact_plan_19).clone()).leaf).clone();
                let __compact_plan_25: bool = (__compact_plan_16).clone() == __compact_plan_24;
                (frame, __compact_plan_25)
            } else {
                let __compact_plan_26: bool = false;
                (frame, __compact_plan_26)
            };
            if !__compact_plan_27 {
                return Err(runtime::CompactError::AssertionFailed(
                    "spend: Illegal state: merkle path not recognized by public state".to_owned(),
                ));
            }
            let (frame, __compact_plan_28): (_, crate::types::coin_info) = frame
                .try_witness_metered(|context, meter| {
                    witnesses.context_new_coin_info(context.witness_context_with(
                        super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        },
                    ))
                })?;
            let __compact_plan_29: crate::types::coin_info = __compact_plan_28;
            let __compact_plan_30: crate::types::coin_info = (__compact_plan_29).clone();
            let __compact_plan_31: crate::types::zk_public_key =
                (((__compact_param_0).clone()).zk).clone();
            let __compact_plan_32: crate::types::zk_public_key = __compact_plan_31;
            let __compact_plan_33: crate::types::commitment =
                crate::pure_circuits::commitment_from_coin_info(
                    __compact_plan_30,
                    __compact_plan_32,
                )?;
            let __compact_plan_34: crate::types::commitment = __compact_plan_33;
            let frame = crate::ledger_slots::commitments
                .record_insert(frame, (__compact_plan_34).clone())?;
            let __compact_plan_35: runtime::OpaqueBytes =
                (((__compact_param_0).clone()).encryption).clone();
            let __compact_plan_36: runtime::OpaqueBytes = __compact_plan_35;
            let __compact_plan_37: crate::types::coin_info = (__compact_plan_29).clone();
            let (frame, __compact_plan_38): (_, runtime::OpaqueBytes) =
                frame.try_witness_metered(|context, meter| {
                    witnesses.context_encrypt(
                        context.witness_context_with(super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        }),
                        __compact_plan_36,
                        __compact_plan_37,
                    )
                })?;
            let __compact_plan_39: runtime::OpaqueBytes = __compact_plan_38;
            let frame = crate::ledger_slots::ciphertexts
                .record_write(frame, (__compact_plan_39).clone())?;
            let __compact_plan_40: crate::types::coin_info = (__compact_param_1).clone();
            let (frame, __compact_plan_41): (_, ()) =
                frame.try_witness_metered(|context, meter| {
                    witnesses.private_remove_coin(
                        context.witness_context_with(super::LedgerView {
                            state: context.query.state.get_ref(),
                            meter,
                        }),
                        __compact_plan_40,
                    )
                })?;
            Ok(frame.finish(()))
        }
        pub fn zerocash_mint<Private, W: super::TryWitnesses<Private>>(
            context: runtime::context::CircuitContext<Private>,
            witnesses: &W,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let (frame, __compact_witness_0) = frame.try_witness_metered(|context, meter| {
                witnesses.context_new_coin_info(context.witness_context_with(super::LedgerView {
                    state: context.query.state.get_ref(),
                    meter,
                }))
            })?;
            let (frame, __compact_witness_1) = frame.try_witness_metered(|context, meter| {
                witnesses.private_zk_public_key(context.witness_context_with(super::LedgerView {
                    state: context.query.state.get_ref(),
                    meter,
                }))
            })?;
            let __compact_recorded_witness_arg_2: crate::types::coin_info =
                (__compact_witness_0).clone();
            let (frame, _) = frame.try_witness_metered(|context, meter| {
                witnesses.private_add_coin(
                    context.witness_context_with(super::LedgerView {
                        state: context.query.state.get_ref(),
                        meter,
                    }),
                    __compact_recorded_witness_arg_2,
                )
            })?;
            let __compact_recorded_struct_value_3: crate::types::commitment =
                crate::pure_circuits::commitment_from_coin_info(
                    (__compact_witness_0).clone(),
                    (__compact_witness_1).clone(),
                )?;
            let frame = crate::ledger_slots::commitments
                .record_insert(frame, (__compact_recorded_struct_value_3).clone())?;
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {}
        /// A recording handle with access to the contract's witnesses.
        pub struct BorrowedContract<'a, W> {
            pub(super) witnesses: &'a W,
        }
        impl<W> BorrowedContract<'_, W> {
            pub fn spend<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                dest_public_key: crate::types::public_key,
                input_coin: crate::types::coin_info,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            where
                W: super::TryWitnesses<Private>,
            {
                spend(context, self.witnesses, dest_public_key, input_coin)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn spend_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                dest_public_key: crate::types::public_key,
                input_coin: crate::types::coin_info,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            >
            where
                W: super::TryWitnesses<Private>,
            {
                let input = runtime::fab::AlignedValue::from((
                    (dest_public_key).clone(),
                    (input_coin).clone(),
                ));
                let recorded = self.spend(
                    observed.circuit_context(private_state),
                    dest_public_key,
                    input_coin,
                )?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "spend", input,
                ))
            }
            pub fn zerocash_mint<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            where
                W: super::TryWitnesses<Private>,
            {
                zerocash_mint(context, self.witnesses)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn zerocash_mint_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            >
            where
                W: super::TryWitnesses<Private>,
            {
                let input = runtime::fab::AlignedValue::from(());
                let recorded = self.zerocash_mint(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "zerocash_mint",
                    input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn spend<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            dest_public_key: crate::types::public_key,
            input_coin: crate::types::coin_info,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::spend(context, &self.witnesses, dest_public_key, input_coin)
        }
        pub fn zerocash_mint<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::zerocash_mint(context, &self.witnesses)
        }
        /// Borrow the contract's witnesses for a replayable circuit call.
        pub fn recording(&self) -> recorded::BorrowedContract<'_, W> {
            recorded::BorrowedContract {
                witnesses: &self.witnesses,
            }
        }
    }
}
