// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchnorrHashInput {
    pub ann_x: Fr,
    pub ann_y: Fr,
    pub pk_x: Fr,
    pub pk_y: Fr,
    pub msg: [Fr; 4],
}
impl Aligned for SchnorrHashInput {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchnorrHashInput {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.ann_x.field_repr(writer);
        self.ann_y.field_repr(writer);
        self.pk_x.field_repr(writer);
        self.pk_y.field_repr(writer);
        for _e in self.msg.iter() {
            _e.field_repr(writer);
        }
    }
    fn field_size(&self) -> usize {
        self.ann_x.field_size()
            + self.ann_y.field_size()
            + self.pk_x.field_size()
            + self.pk_y.field_size()
            + self.msg.iter().map(|e| e.field_size()).sum::<usize>()
    }
}
impl FromFieldRepr for SchnorrHashInput {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE
        + <Fr as FromFieldRepr>::FIELD_SIZE
        + <Fr as FromFieldRepr>::FIELD_SIZE
        + <Fr as FromFieldRepr>::FIELD_SIZE
        + <Fr as FromFieldRepr>::FIELD_SIZE * 4;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let ann_x = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let ann_y = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let pk_x = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let pk_y = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let msg = compact_runtime::array_from_field_repr::<Fr, 4>(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE * 4],
            <Fr as FromFieldRepr>::FIELD_SIZE,
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE * 4;
        let _ = _offset;
        Some(SchnorrHashInput {
            ann_x,
            ann_y,
            pk_x,
            pk_y,
            msg,
        })
    }
}
impl From<SchnorrHashInput> for compact_runtime::Value {
    fn from(s: SchnorrHashInput) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.ann_x));
        _v.push(compact_runtime::Value::from(s.ann_y));
        _v.push(compact_runtime::Value::from(s.pk_x));
        _v.push(compact_runtime::Value::from(s.pk_y));
        for _e in s.msg.iter() {
            _v.push(compact_runtime::Value::from(_e.clone()));
        }
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for SchnorrHashInput {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.ann_x.binary_repr(writer);
        self.ann_y.binary_repr(writer);
        self.pk_x.binary_repr(writer);
        self.pk_y.binary_repr(writer);
        for _e in self.msg.iter() {
            _e.binary_repr(writer);
        }
    }
    fn binary_len(&self) -> usize {
        self.ann_x.binary_len()
            + self.ann_y.binary_len()
            + self.pk_x.binary_len()
            + self.pk_y.binary_len()
            + self.msg.iter().map(|e| e.binary_len()).sum::<usize>()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct AttestationDomain {
    pub domain: [u8; 32],
}
impl Aligned for AttestationDomain {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for AttestationDomain {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domain.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.domain.field_size()
    }
}
impl FromFieldRepr for AttestationDomain {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let domain = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(AttestationDomain { domain })
    }
}
impl From<AttestationDomain> for compact_runtime::Value {
    fn from(s: AttestationDomain) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.domain));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for AttestationDomain {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.domain.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.domain.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct AttestationSubject {
    pub subject: [u8; 32],
    pub epoch: u64,
}
impl Aligned for AttestationSubject {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for AttestationSubject {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.subject.field_repr(writer);
        self.epoch.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.subject.field_size() + self.epoch.field_size()
    }
}
impl FromFieldRepr for AttestationSubject {
    const FIELD_SIZE: usize =
        <[u8; 32] as FromFieldRepr>::FIELD_SIZE + <u64 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let subject = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let epoch = <u64 as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(AttestationSubject { subject, epoch })
    }
}
impl From<AttestationSubject> for compact_runtime::Value {
    fn from(s: AttestationSubject) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.subject));
        _v.push(compact_runtime::Value::from(s.epoch));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for AttestationSubject {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.subject.binary_repr(writer);
        self.epoch.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.subject.binary_len() + self.epoch.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct AttestationPayload {
    pub payloadHash: Fr,
}
impl Aligned for AttestationPayload {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for AttestationPayload {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.payloadHash.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.payloadHash.field_size()
    }
}
impl FromFieldRepr for AttestationPayload {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let payloadHash = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(AttestationPayload { payloadHash })
    }
}
impl From<AttestationPayload> for compact_runtime::Value {
    fn from(s: AttestationPayload) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.payloadHash));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for AttestationPayload {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.payloadHash.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.payloadHash.binary_len()
    }
}

pub trait Witnesses<PS> {
    fn get_schnorr_reduction<'a>(
        &self,
        ctx: &WitnessContext<Ledger<'a>, PS>,
        challenge_hash: Fr,
    ) -> (PS, (u8, u128));
    fn local_attestor_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, JubjubPoint);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell(compact_runtime::JubjubPoint::default()),
            new_cell(0u64),
            new_cell(false),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, compact_runtime::ContractAddress::default());
        let _witness_ctx_0 =
            WitnessContext::new(ledger(&qctx.state), ctx.initial_private_state, &qctx);
        let (current_private_state, tmp) = self.witnesses.local_attestor_key(&_witness_ctx_0);
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(2u8))
            .push(true, new_cell(true))
            .ins(false, 1)
            .push(false, new_cell(0u8))
            .push(true, new_cell(tmp.clone()))
            .ins(false, 1)
            .build();

        let results = query_for_verify(&qctx, &ops, ctx.gas_limit.clone(), &ctx.cost_model)?;

        Ok(ConstructorResult {
            current_contract_state: results.context.state,
            current_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub(crate) fn schnorr_verify_digest(
        &self,
        ctx: CircuitContext<PS>,
        digest: [Fr; 4],
        signature: compact_runtime::SchnorrSignature,
        pk: JubjubPoint,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let mut __gas_acc = compact_runtime::RunningCost::default();
        let _cr_1 =
            compact_runtime::schnorr_verify_jubjub(ctx, digest, signature.clone(), pk.clone())?;
        let ctx = _cr_1.context;
        __gas_acc += _cr_1.gas_cost.clone();
        let ops = OpProgramVerify::<DefaultDB>::new().build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: __gas_acc + results.gas_cost,
        })
    }

    pub fn verify_attestation(
        &self,
        ctx: CircuitContext<PS>,
        digest: [Fr; 4],
        signature: compact_runtime::SchnorrSignature,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let mut __gas_acc = compact_runtime::RunningCost::default();
        compact_assert!(
            {
                let _gather_ops = OpProgramGather::<DefaultDB>::new()
                    .dup(0)
                    .idx_at_index(2u8, false)
                    .popeq(false)
                    .build();
                let _gather_results = query_for_read(
                    &ctx.current_query_context,
                    &_gather_ops,
                    None,
                    &initial_cost_model(),
                )
                .map_err(|e| {
                    CompactError::AssertionFailed(format!("ledger query failed: {:?}", e))
                })?;
                let _av = match _gather_results.events.last() {
                    Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                    _ => {
                        return Err(CompactError::AssertionFailed(
                            "ledger: expected Read event".into(),
                        ))
                    }
                };
                compact_runtime::std_lib::decode_bool(_av)?
            },
            "attestor is closed"
        );
        let _carg_2_2 = {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(0u8, false)
                .popeq(false)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => {
                    return Err(CompactError::AssertionFailed(
                        "ledger: expected Read event".into(),
                    ))
                }
            };
            compact_runtime::std_lib::decode_jubjub_point(_av)?
        };
        let _cr_2 = self.schnorr_verify_digest(ctx, digest, signature.clone(), _carg_2_2)?;
        let ctx = _cr_2.context;
        __gas_acc += _cr_2.gas_cost.clone();
        let ops = OpProgramVerify::<DefaultDB>::new().build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: __gas_acc + results.gas_cost,
        })
    }

    pub fn accept_attestation(
        &self,
        ctx: CircuitContext<PS>,
        digest: [Fr; 4],
        signature: compact_runtime::SchnorrSignature,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let mut __gas_acc = compact_runtime::RunningCost::default();
        compact_assert!(
            {
                let _gather_ops = OpProgramGather::<DefaultDB>::new()
                    .dup(0)
                    .idx_at_index(2u8, false)
                    .popeq(false)
                    .build();
                let _gather_results = query_for_read(
                    &ctx.current_query_context,
                    &_gather_ops,
                    None,
                    &initial_cost_model(),
                )
                .map_err(|e| {
                    CompactError::AssertionFailed(format!("ledger query failed: {:?}", e))
                })?;
                let _av = match _gather_results.events.last() {
                    Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                    _ => {
                        return Err(CompactError::AssertionFailed(
                            "ledger: expected Read event".into(),
                        ))
                    }
                };
                compact_runtime::std_lib::decode_bool(_av)?
            },
            "attestor is closed"
        );
        let _carg_2_2 = {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(0u8, false)
                .popeq(false)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => {
                    return Err(CompactError::AssertionFailed(
                        "ledger: expected Read event".into(),
                    ))
                }
            };
            compact_runtime::std_lib::decode_jubjub_point(_av)?
        };
        let _cr_2 = self.schnorr_verify_digest(ctx, digest, signature.clone(), _carg_2_2)?;
        let ctx = _cr_2.context;
        __gas_acc += _cr_2.gas_cost.clone();
        let tmp = 1u16;
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(1u8, true)
            .addi(tmp.clone() as u32)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: __gas_acc + results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn attestor_key(&self) -> Result<JubjubPoint, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_jubjub_point(av)
    }
    pub fn accepted_count(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u64(av)
    }
    pub fn open(&self) -> Result<bool, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(2u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_bool(av)
    }
}

pub mod pure_circuits {
    use super::*;

    pub fn attestation_digest(
        subject: [u8; 32],
        epoch: u64,
        payload_hash: Fr,
    ) -> Result<[Fr; 4], CompactError> {
        Ok([
            compact_runtime::std_lib::transient_hash_aligned(&[
                compact_runtime::AlignedValue::from(AttestationDomain {
                    domain: [
                        97u8, 115, 115, 101, 116, 45, 97, 116, 116, 101, 115, 116, 97, 116, 105,
                        111, 110, 58, 118, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    ],
                }),
            ]),
            compact_runtime::std_lib::transient_hash_aligned(&[
                compact_runtime::AlignedValue::from(AttestationSubject {
                    subject: subject,
                    epoch: epoch,
                }),
            ]),
            compact_runtime::std_lib::transient_hash_aligned(&[
                compact_runtime::AlignedValue::from(AttestationPayload {
                    payloadHash: payload_hash,
                }),
            ]),
            payload_hash,
        ])
    }
}
