// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Empty {}
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct FieldRepr {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Fr {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct From {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct MemWrite {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Names {
        pub option_value: crate::types::Option,
        pub fr_value: crate::types::Fr,
        pub memwrite_value: crate::types::MemWrite,
        pub runtime_value: crate::types::runtime,
        pub fieldrepr_value: crate::types::FieldRepr,
        pub vec_value: crate::types::Vec,
        pub result_value: crate::types::Result,
        pub from_value: crate::types::From,
        pub empty: crate::types::Empty,
        pub nested: ::midnight_compact_runtime::FixedVector<crate::types::Option, 2>,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Option {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Result {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Vec {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct runtime {
        pub amount: ::midnight_compact_runtime::Field,
        pub active: ::core::primitive::bool,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 50);
    pub fn round_trip(
        value: crate::types::Names,
    ) -> Result<crate::types::Names, runtime::CompactError> {
        Ok(value.clone())
    }
}
