// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub fn constant() -> Result<(runtime::Field, runtime::Field), runtime::CompactError> {
        Ok({
            let __compact_local_0: (runtime::Field, runtime::Field) =
                (runtime::Field::from(3u128), runtime::Field::from(4u128));
            __compact_local_0
        })
    }
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            (runtime::Field, runtime::Field),
            runtime::ledger::DefaultDB,
        >(
            (runtime::Field::from(3u128), runtime::Field::from(4u128)).clone(),
        )]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn read_pair<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<
        runtime::context::CircuitResult<Private, (runtime::Field, runtime::Field)>,
        runtime::CompactError,
    > {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = context.read_cell::<(runtime::Field, runtime::Field)>(0)?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
