// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerkleTreeDigest,
    )]
    pub struct MerkleTreeDigest {
        pub field: runtime::Field,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerklePath,
    )]
    pub struct MerkleTreePath {
        pub leaf: runtime::BoundedUint<255>,
        pub path: runtime::FixedVector<crate::types::MerkleTreePathEntry, 3>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
        runtime::CompactMerklePathEntry,
    )]
    pub struct MerkleTreePathEntry {
        pub sibling: crate::types::MerkleTreeDigest,
        pub goes_left: bool,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 17);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const t: runtime::slots::MerkleSlot<runtime::BoundedUint<255>, 3u8, false> =
        runtime::slots::MerkleSlot::new(&[0u8]);
    pub const h: runtime::slots::MerkleSlot<runtime::BoundedUint<255>, 3u8, true> =
        runtime::slots::MerkleSlot::new(&[1u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 17);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {
        pub fn t(
            &self,
        ) -> Result<
            runtime::ledger::MeteredMerkleTreeView<
                'a,
                crate::types::MerkleTreeDigest,
                runtime::ledger::DefaultDB,
            >,
            runtime::CompactError,
        > {
            runtime::ledger::metered_merkle_tree_view_at_path::<crate::types::MerkleTreeDigest, _>(
                self.meter,
                &[0],
                3,
            )
        }
        pub fn h(
            &self,
        ) -> Result<
            runtime::ledger::MeteredHistoricMerkleTreeView<
                'a,
                crate::types::MerkleTreeDigest,
                runtime::ledger::DefaultDB,
            >,
            runtime::CompactError,
        > {
            runtime::ledger::metered_historic_merkle_tree_view_at_path::<
                crate::types::MerkleTreeDigest,
                _,
            >(self.meter, &[1], 3)
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {
        fn leaf_path(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, crate::types::MerkleTreePath);
        fn historic_path(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, crate::types::MerkleTreePath);
        fn merkle_checks(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, bool);
        fn historic_checks(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
        ) -> (Private, bool);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_merkle_tree(3u8),
            runtime::ledger::constructor_historic_merkle_tree(3u8),
        ]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn append<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.insert(context, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn get_path<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<
        runtime::context::CircuitResult<Private, crate::types::MerkleTreePath>,
        runtime::CompactError,
    > {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.leaf_path(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_0.clone(),
        ));
        let result = __compact_witness_0;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn append_h<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::h.insert(context, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn get_historic_path<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<
        runtime::context::CircuitResult<Private, crate::types::MerkleTreePath>,
        runtime::CompactError,
    > {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.historic_path(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_0.clone(),
        ));
        let result = __compact_witness_0;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn check_witness_merkle<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.merkle_checks(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_0.clone(),
        ));
        let result = __compact_witness_0;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn check_witness_history<Private, W: TryWitnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_witness_meter_0 = runtime::context::WitnessReadMeter::new(&context);
        let (__compact_next_private_0, __compact_witness_0) =
            witnesses.historic_checks(context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
                meter: &__compact_witness_meter_0,
            }))?;
        total_cost += __compact_witness_meter_0.gas_cost();
        context.private_state = __compact_next_private_0;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_0.clone(),
        ));
        let result = __compact_witness_0;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn append<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_insert(frame, __compact_param_0)?;
            Ok(frame.finish(()))
        }
        pub fn append_h<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::h.record_insert(frame, __compact_param_0)?;
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn append<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                __compact_param_0: runtime::BoundedUint<255>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::append(context, __compact_param_0)
            }
            pub fn append_h<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                __compact_param_0: runtime::BoundedUint<255>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::append_h(context, __compact_param_0)
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn append<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append(context, __compact_param_0)
        }
        pub fn get_path<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<
            runtime::context::CircuitResult<Private, crate::types::MerkleTreePath>,
            runtime::CompactError,
        >
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::get_path(context, &self.witnesses)
        }
        pub fn append_h<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append_h(context, __compact_param_0)
        }
        pub fn get_historic_path<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<
            runtime::context::CircuitResult<Private, crate::types::MerkleTreePath>,
            runtime::CompactError,
        >
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::get_historic_path(context, &self.witnesses)
        }
        pub fn check_witness_merkle<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::check_witness_merkle(context, &self.witnesses)
        }
        pub fn check_witness_history<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError>
        where
            W: TryWitnesses<Private>,
        {
            crate::ledger_contract::check_witness_history(context, &self.witnesses)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
