// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct ContractAddress {
        pub bytes: runtime::FixedBytes<32>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct Either {
        pub is_left: bool,
        pub left: crate::types::ZswapCoinPublicKey,
        pub right: crate::types::ContractAddress,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct QualifiedShieldedCoinInfo {
        pub nonce: runtime::FixedBytes<32>,
        pub color: runtime::FixedBytes<32>,
        pub value: runtime::BoundedUint<340282366920938463463374607431768211455>,
        pub mt_index: runtime::BoundedUint<18446744073709551615>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct ShieldedCoinInfo {
        pub nonce: runtime::FixedBytes<32>,
        pub color: runtime::FixedBytes<32>,
        pub value: runtime::BoundedUint<340282366920938463463374607431768211455>,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct ZswapCoinPublicKey {
        pub bytes: runtime::FixedBytes<32>,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 45);
    pub(crate) fn right(
        value: crate::types::ContractAddress,
    ) -> Result<crate::types::Either, runtime::CompactError> {
        Ok(crate::types::Either {
            is_left: false,
            left: <crate::types::ZswapCoinPublicKey as Default>::default(),
            right: value.clone(),
        })
    }
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const c: runtime::slots::SetSlot<crate::types::QualifiedShieldedCoinInfo> =
        runtime::slots::SetSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 45);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Inspect this declared Set in the borrowed public state.
        pub fn c(
            &self,
        ) -> Result<
            runtime::ledger::SetView<'a, crate::types::QualifiedShieldedCoinInfo, D>,
            runtime::CompactError,
        > {
            crate::ledger_slots::c.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_set()]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn test_QualifiedShieldedCoinInfo<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_struct_member_0: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_1: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_2: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_struct_member_3: runtime::BoundedUint<18446744073709551615> =
            runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_0: crate::types::QualifiedShieldedCoinInfo =
            crate::types::QualifiedShieldedCoinInfo {
                nonce: __compact_struct_member_0,
                color: __compact_struct_member_1,
                value: __compact_struct_member_2,
                mt_index: __compact_struct_member_3,
            };
        let __compact_struct_member_4: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_5: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_6: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_struct_member_7: runtime::BoundedUint<18446744073709551615> =
            runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_1: crate::types::QualifiedShieldedCoinInfo =
            crate::types::QualifiedShieldedCoinInfo {
                nonce: __compact_struct_member_4,
                color: __compact_struct_member_5,
                value: __compact_struct_member_6,
                mt_index: __compact_struct_member_7,
            };
        let mut context = context;
        let __compact_query_8 = crate::ledger_slots::c.is_empty(context)?;
        context = __compact_query_8.context;
        total_cost += __compact_query_8.gas_cost;
        let __compact_value_9 = __compact_query_8.result;
        if !(__compact_value_9 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Structure should be empty".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_10 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_10.context;
        total_cost += __compact_query_10.gas_cost;
        let __compact_value_11 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_10.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_11
            == runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 0".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.insert(context, __compact_action_local_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_12 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_12.context;
        total_cost += __compact_query_12.gas_cost;
        let __compact_value_13 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_12.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_13
            == runtime::BoundedUint::<18446744073709551615>::new(1u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 1".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_14 =
            crate::ledger_slots::c.member(context, (__compact_action_local_0.clone()).clone())?;
        context = __compact_query_14.context;
        total_cost += __compact_query_14.gas_cost;
        let __compact_value_15 = __compact_query_14.result;
        if !(__compact_value_15 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key qcoin should be member".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.insert(context, __compact_action_local_1.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_16 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_16.context;
        total_cost += __compact_query_16.gas_cost;
        let __compact_value_17 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_16.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_17
            == runtime::BoundedUint::<18446744073709551615>::new(2u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 2".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_18 =
            crate::ledger_slots::c.member(context, (__compact_action_local_1.clone()).clone())?;
        context = __compact_query_18.context;
        total_cost += __compact_query_18.gas_cost;
        let __compact_value_19 = __compact_query_18.result;
        if !(__compact_value_19 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key qcoin2 should be member".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.remove(context, __compact_action_local_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_20 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_20.context;
        total_cost += __compact_query_20.gas_cost;
        let __compact_value_21 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_20.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_21
            == runtime::BoundedUint::<18446744073709551615>::new(1u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 1".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_22 =
            crate::ledger_slots::c.member(context, (__compact_action_local_1.clone()).clone())?;
        context = __compact_query_22.context;
        total_cost += __compact_query_22.gas_cost;
        let __compact_value_23 = __compact_query_22.result;
        if !(__compact_value_23 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key 1 should be member".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.reset(context)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_24 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_24.context;
        total_cost += __compact_query_24.gas_cost;
        let __compact_value_25 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_24.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_25
            == runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 0".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_26 = crate::ledger_slots::c.is_empty(context)?;
        context = __compact_query_26.context;
        total_cost += __compact_query_26.gas_cost;
        let __compact_value_27 = __compact_query_26.result;
        if !(__compact_value_27 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Structure should be empty".to_owned(),
            ));
        }
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn test_ShieldedCoinInfo<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_struct_member_0: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_1: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_2: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_0: crate::types::ShieldedCoinInfo =
            crate::types::ShieldedCoinInfo {
                nonce: __compact_struct_member_0,
                color: __compact_struct_member_1,
                value: __compact_struct_member_2,
            };
        let __compact_struct_member_3: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_4: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_5: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_1: crate::types::ShieldedCoinInfo =
            crate::types::ShieldedCoinInfo {
                nonce: __compact_struct_member_3,
                color: __compact_struct_member_4,
                value: __compact_struct_member_5,
            };
        let __compact_struct_member_6: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_7: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_8: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_struct_member_9: runtime::BoundedUint<18446744073709551615> =
            runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_2: crate::types::QualifiedShieldedCoinInfo =
            crate::types::QualifiedShieldedCoinInfo {
                nonce: __compact_struct_member_6,
                color: __compact_struct_member_7,
                value: __compact_struct_member_8,
                mt_index: __compact_struct_member_9,
            };
        let __compact_struct_member_10: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_11: runtime::FixedBytes<32> = runtime::FixedBytes::new([
            99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
            0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
        ]);
        let __compact_struct_member_12: runtime::BoundedUint<
            340282366920938463463374607431768211455,
        > = runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
            .expect("Compact Uint literal fits its maximum");
        let __compact_struct_member_13: runtime::BoundedUint<18446744073709551615> =
            runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum");
        let __compact_action_local_3: crate::types::QualifiedShieldedCoinInfo =
            crate::types::QualifiedShieldedCoinInfo {
                nonce: __compact_struct_member_10,
                color: __compact_struct_member_11,
                value: __compact_struct_member_12,
                mt_index: __compact_struct_member_13,
            };
        let mut context = context;
        let __compact_query_14 = crate::ledger_slots::c.is_empty(context)?;
        context = __compact_query_14.context;
        total_cost += __compact_query_14.gas_cost;
        let __compact_value_15 = __compact_query_14.result;
        if !(__compact_value_15 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Structure should be empty".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_16 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_16.context;
        total_cost += __compact_query_16.gas_cost;
        let __compact_value_17 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_16.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_17
            == runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 0".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_18 = context.kernel_self()?;
        context = __compact_query_18.context;
        total_cost += __compact_query_18.gas_cost;
        let __compact_call_argument_19 = crate::types::ContractAddress {
            bytes: runtime::ledger::contract_address_bytes(&__compact_query_18.result),
        };
        let __compact_action_local_4: crate::types::Either =
            crate::pure_circuits::right(__compact_call_argument_19)?;
        let __compact_coin_20 = __compact_action_local_0.clone();
        let __compact_recipient_21 = __compact_action_local_4.clone();
        let step = crate::ledger_slots::c.insert_coin(
            context,
            runtime::ledger::coin_info_from_compact(
                __compact_coin_20.nonce,
                __compact_coin_20.color,
                __compact_coin_20.value.value(),
            ),
            runtime::ledger::coin_recipient_from_compact(
                __compact_recipient_21.is_left,
                __compact_recipient_21.left.bytes,
                __compact_recipient_21.right.bytes,
            ),
        )?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_22 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_22.context;
        total_cost += __compact_query_22.gas_cost;
        let __compact_value_23 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_22.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_23
            == runtime::BoundedUint::<18446744073709551615>::new(1u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 1".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_24 =
            crate::ledger_slots::c.member(context, (__compact_action_local_2.clone()).clone())?;
        context = __compact_query_24.context;
        total_cost += __compact_query_24.gas_cost;
        let __compact_value_25 = __compact_query_24.result;
        if !(__compact_value_25 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key coin should be member".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_26 = context.kernel_self()?;
        context = __compact_query_26.context;
        total_cost += __compact_query_26.gas_cost;
        let __compact_call_argument_27 = crate::types::ContractAddress {
            bytes: runtime::ledger::contract_address_bytes(&__compact_query_26.result),
        };
        let __compact_action_local_5: crate::types::Either =
            crate::pure_circuits::right(__compact_call_argument_27)?;
        let __compact_coin_28 = __compact_action_local_1.clone();
        let __compact_recipient_29 = __compact_action_local_5.clone();
        let step = crate::ledger_slots::c.insert_coin(
            context,
            runtime::ledger::coin_info_from_compact(
                __compact_coin_28.nonce,
                __compact_coin_28.color,
                __compact_coin_28.value.value(),
            ),
            runtime::ledger::coin_recipient_from_compact(
                __compact_recipient_29.is_left,
                __compact_recipient_29.left.bytes,
                __compact_recipient_29.right.bytes,
            ),
        )?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_30 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_30.context;
        total_cost += __compact_query_30.gas_cost;
        let __compact_value_31 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_30.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_31
            == runtime::BoundedUint::<18446744073709551615>::new(2u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 2".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_32 =
            crate::ledger_slots::c.member(context, (__compact_action_local_3.clone()).clone())?;
        context = __compact_query_32.context;
        total_cost += __compact_query_32.gas_cost;
        let __compact_value_33 = __compact_query_32.result;
        if !(__compact_value_33 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key coin2 should be member".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.remove(context, __compact_action_local_2.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_34 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_34.context;
        total_cost += __compact_query_34.gas_cost;
        let __compact_value_35 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_34.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_35
            == runtime::BoundedUint::<18446744073709551615>::new(1u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 1".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_36 =
            crate::ledger_slots::c.member(context, (__compact_action_local_3.clone()).clone())?;
        context = __compact_query_36.context;
        total_cost += __compact_query_36.gas_cost;
        let __compact_value_37 = __compact_query_36.result;
        if !(__compact_value_37 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Key coin2 should be member".to_owned(),
            ));
        }
        let step = crate::ledger_slots::c.reset(context)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let mut context = context;
        let __compact_query_38 = crate::ledger_slots::c.size(context)?;
        context = __compact_query_38.context;
        total_cost += __compact_query_38.gas_cost;
        let __compact_value_39 =
            runtime::BoundedUint::<18446744073709551615>::new(__compact_query_38.result as u128)
                .expect("ledger Set size fits Uint<64>");
        if !(__compact_value_39
            == runtime::BoundedUint::<18446744073709551615>::new(0u128)
                .expect("Compact Uint literal fits its maximum"))
        {
            return Err(runtime::CompactError::AssertionFailed(
                "Size should be 0".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_40 = crate::ledger_slots::c.is_empty(context)?;
        context = __compact_query_40.context;
        total_cost += __compact_query_40.gas_cost;
        let __compact_value_41 = __compact_query_40.result;
        if !(__compact_value_41 == true) {
            return Err(runtime::CompactError::AssertionFailed(
                "Structure should be empty".to_owned(),
            ));
        }
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn test_QualifiedShieldedCoinInfo<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_plan_0: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_1: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_2: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_3: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_4: crate::types::QualifiedShieldedCoinInfo =
                crate::types::QualifiedShieldedCoinInfo {
                    nonce: __compact_plan_0,
                    color: __compact_plan_1,
                    value: __compact_plan_2,
                    mt_index: __compact_plan_3,
                };
            let __compact_plan_5: crate::types::QualifiedShieldedCoinInfo = __compact_plan_4;
            let __compact_plan_6: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_7: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_8: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_9: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_10: crate::types::QualifiedShieldedCoinInfo =
                crate::types::QualifiedShieldedCoinInfo {
                    nonce: __compact_plan_6,
                    color: __compact_plan_7,
                    value: __compact_plan_8,
                    mt_index: __compact_plan_9,
                };
            let __compact_plan_11: crate::types::QualifiedShieldedCoinInfo = __compact_plan_10;
            let (frame, __compact_plan_12): (_, bool) =
                crate::ledger_slots::c.record_is_empty(frame)?;
            let __compact_plan_13: bool = true;
            let __compact_plan_14: bool = __compact_plan_12 == __compact_plan_13;
            if !__compact_plan_14 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Structure should be empty".to_owned(),
                ));
            }
            let (frame, __compact_plan_15) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_16: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_15 as u128)?;
            let __compact_plan_17: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_18: bool = __compact_plan_16 == __compact_plan_17;
            if !__compact_plan_18 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 0".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_insert(frame, (__compact_plan_5).clone())?;
            let (frame, __compact_plan_19) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_20: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_19 as u128)?;
            let __compact_plan_21: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_22: bool = __compact_plan_20 == __compact_plan_21;
            if !__compact_plan_22 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 1".to_owned(),
                ));
            }
            let (frame, __compact_plan_23): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_5).clone())?;
            let __compact_plan_24: bool = true;
            let __compact_plan_25: bool = __compact_plan_23 == __compact_plan_24;
            if !__compact_plan_25 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key qcoin should be member".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_insert(frame, (__compact_plan_11).clone())?;
            let (frame, __compact_plan_26) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_27: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_26 as u128)?;
            let __compact_plan_28: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(2u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_29: bool = __compact_plan_27 == __compact_plan_28;
            if !__compact_plan_29 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 2".to_owned(),
                ));
            }
            let (frame, __compact_plan_30): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_11).clone())?;
            let __compact_plan_31: bool = true;
            let __compact_plan_32: bool = __compact_plan_30 == __compact_plan_31;
            if !__compact_plan_32 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key qcoin2 should be member".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_remove(frame, (__compact_plan_5).clone())?;
            let (frame, __compact_plan_33) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_34: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_33 as u128)?;
            let __compact_plan_35: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_36: bool = __compact_plan_34 == __compact_plan_35;
            if !__compact_plan_36 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 1".to_owned(),
                ));
            }
            let (frame, __compact_plan_37): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_11).clone())?;
            let __compact_plan_38: bool = true;
            let __compact_plan_39: bool = __compact_plan_37 == __compact_plan_38;
            if !__compact_plan_39 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key 1 should be member".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_reset(frame)?;
            let (frame, __compact_plan_40) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_41: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_40 as u128)?;
            let __compact_plan_42: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_43: bool = __compact_plan_41 == __compact_plan_42;
            if !__compact_plan_43 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 0".to_owned(),
                ));
            }
            let (frame, __compact_plan_44): (_, bool) =
                crate::ledger_slots::c.record_is_empty(frame)?;
            let __compact_plan_45: bool = true;
            let __compact_plan_46: bool = __compact_plan_44 == __compact_plan_45;
            if !__compact_plan_46 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Structure should be empty".to_owned(),
                ));
            }
            Ok(frame.finish(()))
        }
        pub fn test_ShieldedCoinInfo<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let __compact_plan_0: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_1: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_2: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_3: crate::types::ShieldedCoinInfo = crate::types::ShieldedCoinInfo {
                nonce: __compact_plan_0,
                color: __compact_plan_1,
                value: __compact_plan_2,
            };
            let __compact_plan_4: crate::types::ShieldedCoinInfo = __compact_plan_3;
            let __compact_plan_5: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_6: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_7: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_8: crate::types::ShieldedCoinInfo = crate::types::ShieldedCoinInfo {
                nonce: __compact_plan_5,
                color: __compact_plan_6,
                value: __compact_plan_7,
            };
            let __compact_plan_9: crate::types::ShieldedCoinInfo = __compact_plan_8;
            let __compact_plan_10: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_11: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_12: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_13: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_14: crate::types::QualifiedShieldedCoinInfo =
                crate::types::QualifiedShieldedCoinInfo {
                    nonce: __compact_plan_10,
                    color: __compact_plan_11,
                    value: __compact_plan_12,
                    mt_index: __compact_plan_13,
                };
            let __compact_plan_15: crate::types::QualifiedShieldedCoinInfo = __compact_plan_14;
            let __compact_plan_16: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                110u8, 111u8, 110u8, 99u8, 101u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_17: runtime::FixedBytes<32> = runtime::FixedBytes::new([
                99u8, 111u8, 108u8, 111u8, 114u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8,
                0u8,
            ]);
            let __compact_plan_18: runtime::BoundedUint<340282366920938463463374607431768211455> =
                runtime::BoundedUint::<340282366920938463463374607431768211455>::new(2u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_19: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_20: crate::types::QualifiedShieldedCoinInfo =
                crate::types::QualifiedShieldedCoinInfo {
                    nonce: __compact_plan_16,
                    color: __compact_plan_17,
                    value: __compact_plan_18,
                    mt_index: __compact_plan_19,
                };
            let __compact_plan_21: crate::types::QualifiedShieldedCoinInfo = __compact_plan_20;
            let (frame, __compact_plan_22): (_, bool) =
                crate::ledger_slots::c.record_is_empty(frame)?;
            let __compact_plan_23: bool = true;
            let __compact_plan_24: bool = __compact_plan_22 == __compact_plan_23;
            if !__compact_plan_24 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Structure should be empty".to_owned(),
                ));
            }
            let (frame, __compact_plan_25) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_26: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_25 as u128)?;
            let __compact_plan_27: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_28: bool = __compact_plan_26 == __compact_plan_27;
            if !__compact_plan_28 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 0".to_owned(),
                ));
            }
            let (frame, __compact_plan_29) = frame.kernel_self()?;
            let __compact_plan_30: crate::types::ContractAddress = crate::types::ContractAddress {
                bytes: runtime::ledger::contract_address_bytes(&__compact_plan_29),
            };
            let __compact_plan_31: crate::types::ContractAddress = __compact_plan_30;
            let __compact_plan_32: crate::types::Either =
                crate::pure_circuits::right(__compact_plan_31)?;
            let __compact_plan_33: crate::types::Either = __compact_plan_32;
            let frame = crate::ledger_slots::c.record_insert_coin(
                frame,
                runtime::ledger::coin_info_from_compact(
                    (__compact_plan_4).clone().nonce,
                    (__compact_plan_4).clone().color,
                    (__compact_plan_4).clone().value.value(),
                ),
                runtime::ledger::coin_recipient_from_compact(
                    (__compact_plan_33).clone().is_left,
                    (__compact_plan_33).clone().left.bytes,
                    (__compact_plan_33).clone().right.bytes,
                ),
            )?;
            let (frame, __compact_plan_34) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_35: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_34 as u128)?;
            let __compact_plan_36: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_37: bool = __compact_plan_35 == __compact_plan_36;
            if !__compact_plan_37 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 1".to_owned(),
                ));
            }
            let (frame, __compact_plan_38): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_15).clone())?;
            let __compact_plan_39: bool = true;
            let __compact_plan_40: bool = __compact_plan_38 == __compact_plan_39;
            if !__compact_plan_40 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key coin should be member".to_owned(),
                ));
            }
            let (frame, __compact_plan_41) = frame.kernel_self()?;
            let __compact_plan_42: crate::types::ContractAddress = crate::types::ContractAddress {
                bytes: runtime::ledger::contract_address_bytes(&__compact_plan_41),
            };
            let __compact_plan_43: crate::types::ContractAddress = __compact_plan_42;
            let __compact_plan_44: crate::types::Either =
                crate::pure_circuits::right(__compact_plan_43)?;
            let __compact_plan_45: crate::types::Either = __compact_plan_44;
            let frame = crate::ledger_slots::c.record_insert_coin(
                frame,
                runtime::ledger::coin_info_from_compact(
                    (__compact_plan_9).clone().nonce,
                    (__compact_plan_9).clone().color,
                    (__compact_plan_9).clone().value.value(),
                ),
                runtime::ledger::coin_recipient_from_compact(
                    (__compact_plan_45).clone().is_left,
                    (__compact_plan_45).clone().left.bytes,
                    (__compact_plan_45).clone().right.bytes,
                ),
            )?;
            let (frame, __compact_plan_46) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_47: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_46 as u128)?;
            let __compact_plan_48: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(2u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_49: bool = __compact_plan_47 == __compact_plan_48;
            if !__compact_plan_49 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 2".to_owned(),
                ));
            }
            let (frame, __compact_plan_50): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_21).clone())?;
            let __compact_plan_51: bool = true;
            let __compact_plan_52: bool = __compact_plan_50 == __compact_plan_51;
            if !__compact_plan_52 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key coin2 should be member".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_remove(frame, (__compact_plan_15).clone())?;
            let (frame, __compact_plan_53) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_54: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_53 as u128)?;
            let __compact_plan_55: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(1u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_56: bool = __compact_plan_54 == __compact_plan_55;
            if !__compact_plan_56 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 1".to_owned(),
                ));
            }
            let (frame, __compact_plan_57): (_, bool) =
                crate::ledger_slots::c.record_member(frame, (__compact_plan_21).clone())?;
            let __compact_plan_58: bool = true;
            let __compact_plan_59: bool = __compact_plan_57 == __compact_plan_58;
            if !__compact_plan_59 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Key coin2 should be member".to_owned(),
                ));
            }
            let frame = crate::ledger_slots::c.record_reset(frame)?;
            let (frame, __compact_plan_60) = crate::ledger_slots::c.record_size(frame)?;
            let __compact_plan_61: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(__compact_plan_60 as u128)?;
            let __compact_plan_62: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(0u128)
                    .expect("Compact Uint literal fits its maximum");
            let __compact_plan_63: bool = __compact_plan_61 == __compact_plan_62;
            if !__compact_plan_63 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Size should be 0".to_owned(),
                ));
            }
            let (frame, __compact_plan_64): (_, bool) =
                crate::ledger_slots::c.record_is_empty(frame)?;
            let __compact_plan_65: bool = true;
            let __compact_plan_66: bool = __compact_plan_64 == __compact_plan_65;
            if !__compact_plan_66 {
                return Err(runtime::CompactError::AssertionFailed(
                    "Structure should be empty".to_owned(),
                ));
            }
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn test_QualifiedShieldedCoinInfo<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::test_QualifiedShieldedCoinInfo(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn test_QualifiedShieldedCoinInfo_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded =
                    self.test_QualifiedShieldedCoinInfo(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "test_QualifiedShieldedCoinInfo",
                    input,
                ))
            }
            pub fn test_ShieldedCoinInfo<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::test_ShieldedCoinInfo(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn test_ShieldedCoinInfo_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded =
                    self.test_ShieldedCoinInfo(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "test_ShieldedCoinInfo",
                    input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn test_QualifiedShieldedCoinInfo<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::test_QualifiedShieldedCoinInfo(context)
        }
        pub fn test_ShieldedCoinInfo<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::test_ShieldedCoinInfo(context)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
