// Generated by compactc. Do not edit.

pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct Box {
        pub f: runtime::Field,
    }
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct Maybe {
        pub is_some: bool,
        pub value: runtime::Field,
    }
    #[allow(non_camel_case_types)]
    #[derive(Clone, Copy, Debug, PartialEq, Eq, CompactCellValue)]
    pub enum Color {
        red,
        green,
        blue,
    }
    impl Default for Color {
        fn default() -> Self {
            Self::red
        }
    }
    impl FieldRepr for Color {
        fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
            let ordinal: u128 = match self {
                Self::red => 0,
                Self::green => 1,
                Self::blue => 2,
            };
            ordinal.field_repr(writer);
        }
        fn field_size(&self) -> usize {
            1
        }
    }
    impl BinaryHashRepr for Color {
        fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
            let ordinal: u128 = match self {
                Self::red => 0,
                Self::green => 1,
                Self::blue => 2,
            };
            writer.write(&ordinal.to_le_bytes()[..1]);
        }
        fn binary_len(&self) -> usize {
            1
        }
    }
    impl FromFieldRepr for Color {
        const FIELD_SIZE: usize = 1;
        fn from_field_repr(repr: &[Fr]) -> Option<Self> {
            let ordinal = <u128 as FromFieldRepr>::from_field_repr(repr)?;
            match ordinal {
                0 => Some(Self::red),
                1 => Some(Self::green),
                2 => Some(Self::blue),
                _ => None,
            }
        }
    }
}
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub(crate) fn some(
        value: runtime::Field,
    ) -> Result<crate::types::Maybe, runtime::CompactError> {
        Ok(crate::types::Maybe {
            is_some: true,
            value: value,
        })
    }
    pub fn idf(x: runtime::Field) -> Result<runtime::Field, runtime::CompactError> {
        Ok(x)
    }
    pub fn constAnnotatedBothLiteral(
        c: bool,
    ) -> Result<runtime::BoundedUint<255>, runtime::CompactError> {
        Ok({
            let __compact_local_0: runtime::BoundedUint<255> =
                runtime::cast_unsigned::<2, 255>(if c {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })?;
            __compact_local_0
        })
    }
    pub fn constUnannotatedSeqLifted(
        c: bool,
        a: runtime::BoundedUint<255>,
    ) -> Result<runtime::BoundedUint<255>, runtime::CompactError> {
        Ok({
            let __compact_local_0: runtime::BoundedUint<255> = if c {
                runtime::subtract_unsigned::<255, 255, 255>(
                    a,
                    runtime::BoundedUint::<255>::new(1u128)
                        .expect("Compact Uint literal fits its maximum"),
                )?
            } else {
                a
            };
            __compact_local_0
        })
    }
    pub fn returnTailMixed(
        c: bool,
        x: runtime::BoundedUint<255>,
    ) -> Result<runtime::BoundedUint<255>, runtime::CompactError> {
        Ok(if c {
            runtime::BoundedUint::<255>::new(5u128).expect("Compact Uint literal fits its maximum")
        } else {
            x
        })
    }
    pub fn returnTailNested(
        c: bool,
        d: bool,
    ) -> Result<runtime::BoundedUint<255>, runtime::CompactError> {
        Ok(runtime::cast_unsigned::<4, 255>(if c {
            runtime::cast_unsigned::<2, 4>(if d {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?
        } else {
            if d {
                runtime::BoundedUint::<4>::new(3u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<4>::new(4u128)
                    .expect("Compact Uint literal fits its maximum")
            }
        })?)
    }
    pub fn assertArg(c: bool, x: runtime::BoundedUint<255>) -> Result<(), runtime::CompactError> {
        Ok({
            {
                if !(if c {
                    x.value()
                        > runtime::BoundedUint::<255>::new(1u128)
                            .expect("Compact Uint literal fits its maximum")
                            .value()
                } else {
                    x.value()
                        > runtime::BoundedUint::<255>::new(2u128)
                            .expect("Compact Uint literal fits its maximum")
                            .value()
                }) {
                    return Err(runtime::CompactError::AssertionFailed(
                        "ternary assert".to_owned(),
                    ));
                }
            };
            ()
        })
    }
    pub fn arithOperand(
        c: bool,
        n: runtime::BoundedUint<255>,
    ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
        Ok(runtime::cast_unsigned::<256, 18446744073709551615>(
            runtime::add_unsigned::<256, 256, 256>(
                runtime::cast_unsigned::<255, 256>(n)?,
                runtime::cast_unsigned::<1, 256>(if c {
                    runtime::BoundedUint::<1>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<1>::new(0u128)
                        .expect("Compact Uint literal fits its maximum")
                })?,
            )?,
        )?)
    }
    pub fn cmpOperand(
        c: bool,
        x: runtime::BoundedUint<255>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(x == runtime::cast_unsigned::<1, 255>(if c {
            runtime::BoundedUint::<1>::new(1u128).expect("Compact Uint literal fits its maximum")
        } else {
            runtime::BoundedUint::<1>::new(0u128).expect("Compact Uint literal fits its maximum")
        })?)
    }
    pub fn callArgPure(
        c: bool,
        a: runtime::Field,
        b: runtime::Field,
    ) -> Result<runtime::Field, runtime::CompactError> {
        Ok(crate::pure_circuits::idf(if c { a } else { b })?)
    }
    pub fn callArgCtor(
        c: bool,
        a: runtime::Field,
        b: runtime::Field,
    ) -> Result<crate::types::Maybe, runtime::CompactError> {
        Ok(crate::pure_circuits::some(if c { a } else { b })?)
    }
    pub fn structMember(c: bool) -> Result<crate::types::Box, runtime::CompactError> {
        Ok(crate::types::Box {
            f: runtime::Field::from(
                (if c {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            ),
        })
    }
    pub fn structValuedArms(
        c: bool,
        s1: crate::types::Box,
        s2: crate::types::Box,
    ) -> Result<crate::types::Box, runtime::CompactError> {
        Ok(if c { s1.clone() } else { s2.clone() })
    }
    pub fn vectorElement(
        c: bool,
    ) -> Result<runtime::FixedVector<runtime::Field, 2>, runtime::CompactError> {
        Ok(runtime::FixedVector::new([
            if c {
                runtime::Field::from(
                    (runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum"))
                    .value(),
                )
            } else {
                runtime::Field::from(2u128)
            },
            if c {
                runtime::Field::from(
                    (runtime::BoundedUint::<4>::new(3u128)
                        .expect("Compact Uint literal fits its maximum"))
                    .value(),
                )
            } else {
                runtime::Field::from(4u128)
            },
        ]))
    }
    pub fn nativeArg(
        c: bool,
        a: runtime::Field,
        b: runtime::Field,
    ) -> Result<runtime::JubjubPoint, runtime::CompactError> {
        Ok(runtime::hash_to_curve(if c { a } else { b }))
    }
    pub fn fieldTypedArms(
        c: bool,
        f1: runtime::Field,
        f2: runtime::Field,
    ) -> Result<runtime::Field, runtime::CompactError> {
        Ok(if c { f1 } else { f2 })
    }
    pub fn enumValued(c: bool) -> Result<crate::types::Color, runtime::CompactError> {
        Ok(if c {
            crate::types::Color::red
        } else {
            crate::types::Color::green
        })
    }
    pub fn literalAboveI32(
        c: bool,
    ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
        Ok({
            let __compact_local_0: runtime::BoundedUint<18446744073709551615> =
                runtime::cast_unsigned::<3000000000, 18446744073709551615>(if c {
                    runtime::BoundedUint::<3000000000>::new(3000000000u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<3000000000>::new(0u128)
                        .expect("Compact Uint literal fits its maximum")
                })?;
            __compact_local_0
        })
    }
    pub fn literalAboveU64(
        c: bool,
    ) -> Result<runtime::BoundedUint<340282366920938463463374607431768211455>, runtime::CompactError>
    {
        Ok({
            let __compact_local_0: runtime::BoundedUint<340282366920938463463374607431768211455> =
                if c {
                    runtime::BoundedUint::<340282366920938463463374607431768211455>::new(
                        340282366920938463463374607431768211455u128,
                    )
                    .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<340282366920938463463374607431768211455>::new(0u128)
                        .expect("Compact Uint literal fits its maximum")
                };
            __compact_local_0
        })
    }
    pub fn differingUintWidths(
        c: bool,
        a: runtime::BoundedUint<255>,
        b: runtime::BoundedUint<4294967295>,
    ) -> Result<runtime::BoundedUint<4294967295>, runtime::CompactError> {
        Ok(if c {
            runtime::cast_unsigned::<255, 4294967295>(a)?
        } else {
            b
        })
    }
    pub fn uintArmIntoField(
        c: bool,
        a: runtime::BoundedUint<255>,
        b: runtime::BoundedUint<255>,
    ) -> Result<runtime::Field, runtime::CompactError> {
        Ok(runtime::Field::from((if c { a } else { b }).value()))
    }
    pub fn pick(
        c: runtime::BoundedUint<255>,
    ) -> Result<runtime::BoundedUint<255>, runtime::CompactError> {
        Ok(
            if c.value()
                > runtime::BoundedUint::<255>::new(5u128)
                    .expect("Compact Uint literal fits its maximum")
                    .value()
            {
                runtime::subtract_unsigned::<255, 255, 255>(
                    c,
                    runtime::BoundedUint::<255>::new(10u128)
                        .expect("Compact Uint literal fits its maximum"),
                )?
            } else {
                c
            },
        )
    }
    pub fn walkerReturnTail(c: bool) -> Result<runtime::Field, runtime::CompactError> {
        Ok(runtime::Field::from(
            (if c {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        ))
    }
    pub fn walkerCallCtor(c: bool) -> Result<crate::types::Maybe, runtime::CompactError> {
        Ok(crate::pure_circuits::some(runtime::Field::from(
            (if c {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        ))?)
    }
    pub fn nativeVectorElemTernary(
        c: bool,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::persistent_hash(runtime::FixedVector::new([
            if c {
                runtime::Field::from(1u128)
            } else {
                runtime::Field::from(
                    (runtime::BoundedUint::<1>::new(0u128)
                        .expect("Compact Uint literal fits its maximum"))
                    .value(),
                )
            },
            runtime::Field::from(2u128),
        ])))
    }
    pub fn largeLiteralArithOperand(
        c: bool,
        n: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::BoundedUint<340282366920938463463374607431768211455>, runtime::CompactError>
    {
        Ok(runtime::cast_unsigned::<
            18446744076709551615,
            340282366920938463463374607431768211455,
        >(runtime::add_unsigned::<
            18446744076709551615,
            18446744076709551615,
            18446744076709551615,
        >(
            runtime::cast_unsigned::<18446744073709551615, 18446744076709551615>(n)?,
            runtime::cast_unsigned::<3000000000, 18446744076709551615>(if c {
                runtime::BoundedUint::<3000000000>::new(3000000000u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<3000000000>::new(3000000000u128)
                    .expect("Compact Uint literal fits its maximum")
            })?,
        )?)?)
    }
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {
        pub fn flag(&self) -> Result<bool, runtime::CompactError> {
            runtime::ledger::read_root_cell::<bool, _>(self.state, 0)
        }
        pub fn fieldCell(&self) -> Result<runtime::Field, runtime::CompactError> {
            runtime::ledger::read_root_cell::<runtime::Field, _>(self.state, 1)
        }
        pub fn wideCell(
            &self,
        ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
            runtime::ledger::read_root_cell::<runtime::BoundedUint<18446744073709551615>, _>(
                self.state, 2,
            )
        }
        pub fn vecCell(
            &self,
        ) -> Result<runtime::FixedVector<runtime::Field, 2>, runtime::CompactError> {
            runtime::ledger::read_root_cell::<runtime::FixedVector<runtime::Field, 2>, _>(
                self.state, 3,
            )
        }
        pub fn ops(
            &self,
        ) -> Result<runtime::BoundedUint<18446744073709551615>, runtime::CompactError> {
            let value = runtime::ledger::read_root_cell::<u64, _>(self.state, 4)?;
            runtime::BoundedUint::<18446744073709551615>::new(value as u128)
        }
    }
    pub trait Witnesses<Private> {
        fn echoField(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::Field,
        ) -> (Private, runtime::Field);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
        __compact_constructor_param_0: bool,
        __compact_constructor_param_1: bool,
        __compact_constructor_param_2: runtime::Field,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_cell::<bool, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
            runtime::ledger::constructor_cell::<runtime::Field, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::FixedVector<runtime::Field, 2>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_counter(),
        ]);
        {
            let mut context = runtime::context::ConstructorResult::new(__compact_context, state)
                .into_circuit_context(runtime::ledger::ContractAddress::default());
            let mut total_cost = runtime::context::RunningCost::default();
            let __compact_constructor_local_0: runtime::BoundedUint<255> =
                runtime::cast_unsigned::<2, 255>(if __compact_constructor_param_0 {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })?;
            let __compact_constructor_local_1: runtime::Field = if __compact_constructor_param_0 {
                __compact_constructor_param_2
            } else {
                runtime::Field::from(0u128)
            };
            let __compact_constructor_local_2: crate::types::Box = crate::types::Box {
                f: runtime::Field::from(
                    (if __compact_constructor_param_0 {
                        runtime::BoundedUint::<2>::new(1u128)
                            .expect("Compact Uint literal fits its maximum")
                    } else {
                        runtime::BoundedUint::<2>::new(2u128)
                            .expect("Compact Uint literal fits its maximum")
                    })
                    .value(),
                ),
            };
            let __compact_constructor_local_3: runtime::BoundedUint<4> =
                if __compact_constructor_param_0 {
                    runtime::cast_unsigned::<2, 4>(if __compact_constructor_param_1 {
                        runtime::BoundedUint::<2>::new(1u128)
                            .expect("Compact Uint literal fits its maximum")
                    } else {
                        runtime::BoundedUint::<2>::new(2u128)
                            .expect("Compact Uint literal fits its maximum")
                    })?
                } else {
                    if __compact_constructor_param_1 {
                        runtime::BoundedUint::<4>::new(3u128)
                            .expect("Compact Uint literal fits its maximum")
                    } else {
                        runtime::BoundedUint::<4>::new(4u128)
                            .expect("Compact Uint literal fits its maximum")
                    }
                };
            let __compact_constructor_local_4: runtime::JubjubPoint =
                runtime::hash_to_curve(runtime::Field::from(
                    (if __compact_constructor_param_0 {
                        runtime::BoundedUint::<4>::new(3u128)
                            .expect("Compact Uint literal fits its maximum")
                    } else {
                        runtime::BoundedUint::<4>::new(4u128)
                            .expect("Compact Uint literal fits its maximum")
                    })
                    .value(),
                ));
            let __compact_call_argument_5 = runtime::Field::from(
                (if __compact_constructor_param_0 {
                    runtime::BoundedUint::<8>::new(7u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<8>::new(8u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            );
            let __compact_constructor_local_6: runtime::Field =
                crate::pure_circuits::idf(__compact_call_argument_5)?;
            let __compact_value_7 = runtime::BoundedUint::<1>::new(0u128)
                .expect("Compact Uint literal fits its maximum");
            let __compact_constructor_local_8: bool = __compact_value_7
                == if __compact_constructor_param_0 {
                    runtime::BoundedUint::<1>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<1>::new(0u128)
                        .expect("Compact Uint literal fits its maximum")
                };
            if !(if __compact_constructor_param_0 {
                let __compact_value_9 = __compact_constructor_param_2;
                __compact_value_9 == __compact_constructor_param_2
            } else {
                let __compact_value_10 = __compact_constructor_param_2;
                __compact_value_10 == __compact_constructor_param_2
            }) {
                return Err(runtime::CompactError::AssertionFailed(
                    "ctor ternary assert".to_owned(),
                ));
            }
            let __compact_value_11 = __compact_constructor_local_1;
            let __compact_value_12 = (__compact_constructor_local_2.clone()).f.clone();
            let __compact_value_13 = __compact_value_11 + __compact_value_12;
            let __compact_value_14 = runtime::Field::from((__compact_constructor_local_3).value());
            let __compact_value_15 = __compact_value_13 + __compact_value_14;
            let __compact_value_16 = runtime::jubjub_point_x(__compact_constructor_local_4);
            let __compact_value_17 = __compact_value_15 + __compact_value_16;
            let __compact_value_18 = runtime::Field::from((__compact_constructor_local_0).value());
            let __compact_value_19 = __compact_value_17 + __compact_value_18;
            let __compact_value_20 = __compact_constructor_local_6;
            let __compact_value_21 = __compact_value_19 + __compact_value_20;
            let __compact_value_22 = runtime::Field::from(
                (if __compact_constructor_local_8 {
                    runtime::BoundedUint::<1>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<1>::new(0u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            );
            let __compact_constructor_local_23: runtime::Field =
                __compact_value_21 + __compact_value_22;
            let step = context.write_cell(1, (__compact_constructor_local_23).clone())?;
            context = step.context;
            let __compact_constructor_local_24: runtime::BoundedUint<18446744073709551615> =
                runtime::cast_unsigned::<20, 18446744073709551615>(
                    if __compact_constructor_param_0 {
                        runtime::BoundedUint::<20>::new(10u128)
                            .expect("Compact Uint literal fits its maximum")
                    } else {
                        runtime::BoundedUint::<20>::new(20u128)
                            .expect("Compact Uint literal fits its maximum")
                    },
                )?;
            let step = context.write_cell(2, (__compact_constructor_local_24).clone())?;
            context = step.context;
            let __compact_constructor_local_25: runtime::FixedVector<runtime::Field, 2> =
                runtime::FixedVector::new([
                    if __compact_constructor_param_0 {
                        runtime::Field::from(
                            (runtime::BoundedUint::<2>::new(1u128)
                                .expect("Compact Uint literal fits its maximum"))
                            .value(),
                        )
                    } else {
                        runtime::Field::from(2u128)
                    },
                    if __compact_constructor_param_0 {
                        runtime::Field::from(
                            (runtime::BoundedUint::<4>::new(3u128)
                                .expect("Compact Uint literal fits its maximum"))
                            .value(),
                        )
                    } else {
                        runtime::Field::from(4u128)
                    },
                ]);
            let step = context.write_cell(3, (__compact_constructor_local_25.clone()).clone())?;
            context = step.context;
            let _ = total_cost;
            Ok(context.into_constructor_result())
        }
    }
    pub fn walkerConstAnnotated<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::BoundedUint<255> =
            runtime::cast_unsigned::<2, 255>(if __compact_param_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let __compact_action_local_1: runtime::Field =
            runtime::Field::from((__compact_action_local_0).value());
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerCompareEq<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
        __compact_param_1: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_value_0 = __compact_param_1;
        let __compact_action_local_0: bool = __compact_value_0
            == runtime::cast_unsigned::<1, 255>(if __compact_param_0 {
                runtime::BoundedUint::<1>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<1>::new(0u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let __compact_action_local_1: runtime::Field = if __compact_action_local_0 {
            runtime::Field::from(1u128)
        } else {
            runtime::Field::from(0u128)
        };
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerCallPure<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_call_argument_0 = runtime::Field::from(
            (if __compact_param_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        );
        let __compact_action_local_0: runtime::Field =
            crate::pure_circuits::idf(__compact_call_argument_0)?;
        let step = context.write_cell(1, __compact_action_local_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerStructMember<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: crate::types::Box = crate::types::Box {
            f: runtime::Field::from(
                (if __compact_param_0 {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            ),
        };
        let __compact_action_local_1: runtime::Field = (__compact_action_local_0.clone()).f.clone();
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerWrite<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
        __compact_param_1: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::Field = if __compact_param_0 {
            __compact_param_1
        } else {
            runtime::Field::from(0u128)
        };
        let step = context.write_cell(1, __compact_action_local_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn witnessArg<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = runtime::Field::from(
            (if __compact_param_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        );
        let (__compact_next_private_1, __compact_witness_1) = witnesses.echoField(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let __compact_action_local_0: runtime::Field = __compact_witness_1;
        let step = context.write_cell(1, __compact_action_local_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamIncrement<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: runtime::BoundedUint<65535> =
            runtime::cast_unsigned::<4, 65535>(if __compact_action_local_0 {
                runtime::BoundedUint::<4>::new(3u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<4>::new(4u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let step = context.increment_counter(4, __compact_action_local_1.value() as u16)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let __compact_action_local_2: runtime::BoundedUint<18446744073709551615> =
            runtime::cast_unsigned::<20, 18446744073709551615>(if __compact_action_local_0 {
                runtime::BoundedUint::<20>::new(10u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<20>::new(20u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let step = context.write_cell(2, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamCompareEq<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_value_1 =
            runtime::BoundedUint::<1>::new(1u128).expect("Compact Uint literal fits its maximum");
        let __compact_action_local_1: bool = __compact_value_1
            == if __compact_action_local_0 {
                runtime::BoundedUint::<1>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<1>::new(0u128)
                    .expect("Compact Uint literal fits its maximum")
            };
        let __compact_action_local_2: runtime::Field = if __compact_action_local_1 {
            runtime::Field::from(1u128)
        } else {
            runtime::Field::from(0u128)
        };
        let step = context.write_cell(1, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamWrite<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
        __compact_param_1: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::BoundedUint<65535> =
            runtime::cast_unsigned::<2, 65535>(if __compact_param_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let step = context.increment_counter(4, __compact_action_local_0.value() as u16)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let step = context.write_cell(1, __compact_param_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerVectorElement<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::FixedVector<runtime::Field, 2> =
            runtime::FixedVector::new([
                if __compact_param_0 {
                    runtime::Field::from(
                        (runtime::BoundedUint::<2>::new(1u128)
                            .expect("Compact Uint literal fits its maximum"))
                        .value(),
                    )
                } else {
                    runtime::Field::from(2u128)
                },
                if __compact_param_0 {
                    runtime::Field::from(
                        (runtime::BoundedUint::<4>::new(3u128)
                            .expect("Compact Uint literal fits its maximum"))
                        .value(),
                    )
                } else {
                    runtime::Field::from(4u128)
                },
            ]);
        let step = context.write_cell(3, __compact_action_local_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerNativeArg<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::JubjubPoint =
            runtime::hash_to_curve(runtime::Field::from(
                (if __compact_param_0 {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            ));
        let __compact_action_local_1: runtime::Field =
            runtime::jubjub_point_x(__compact_action_local_0);
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerNestedIf<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
        __compact_param_1: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::BoundedUint<4> = if __compact_param_0 {
            runtime::cast_unsigned::<2, 4>(if __compact_param_1 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?
        } else {
            if __compact_param_1 {
                runtime::BoundedUint::<4>::new(3u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<4>::new(4u128)
                    .expect("Compact Uint literal fits its maximum")
            }
        };
        let __compact_action_local_1: runtime::Field =
            runtime::Field::from((__compact_action_local_0).value());
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn walkerInlineWrite<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: bool,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let __compact_action_local_0: runtime::BoundedUint<65535> =
            runtime::cast_unsigned::<2, 65535>(if __compact_param_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let step = context.increment_counter(4, __compact_action_local_0.value() as u16)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamCallPure<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_call_argument_1 = runtime::Field::from(
            (if __compact_action_local_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        );
        let __compact_action_local_1: runtime::Field =
            crate::pure_circuits::idf(__compact_call_argument_1)?;
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamVectorElement<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: runtime::FixedVector<runtime::Field, 2> =
            runtime::FixedVector::new([
                if __compact_action_local_0 {
                    runtime::Field::from(
                        (runtime::BoundedUint::<2>::new(1u128)
                            .expect("Compact Uint literal fits its maximum"))
                        .value(),
                    )
                } else {
                    runtime::Field::from(2u128)
                },
                if __compact_action_local_0 {
                    runtime::Field::from(
                        (runtime::BoundedUint::<4>::new(3u128)
                            .expect("Compact Uint literal fits its maximum"))
                        .value(),
                    )
                } else {
                    runtime::Field::from(4u128)
                },
            ]);
        let step = context.write_cell(3, __compact_action_local_1.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamNativeArg<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: runtime::JubjubPoint =
            runtime::hash_to_curve(runtime::Field::from(
                (if __compact_action_local_0 {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            ));
        let __compact_action_local_2: runtime::Field =
            runtime::jubjub_point_x(__compact_action_local_1);
        let step = context.write_cell(1, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamStructMember<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: crate::types::Box = crate::types::Box {
            f: runtime::Field::from(
                (if __compact_action_local_0 {
                    runtime::BoundedUint::<2>::new(1u128)
                        .expect("Compact Uint literal fits its maximum")
                } else {
                    runtime::BoundedUint::<2>::new(2u128)
                        .expect("Compact Uint literal fits its maximum")
                })
                .value(),
            ),
        };
        let __compact_action_local_2: runtime::Field = (__compact_action_local_1.clone()).f.clone();
        let step = context.write_cell(1, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamCallWitness<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let mut context = context;
        let __compact_argument_1 = runtime::Field::from(
            (if __compact_action_local_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })
            .value(),
        );
        let (__compact_next_private_2, __compact_witness_2) = witnesses.echoField(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_1,
        );
        context.private_state = __compact_next_private_2;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_2.clone(),
        ));
        let __compact_action_local_1: runtime::Field = __compact_witness_2;
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamConstAnnotated<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: runtime::BoundedUint<65535> =
            runtime::cast_unsigned::<2, 65535>(if __compact_action_local_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?;
        let step = context.increment_counter(4, __compact_action_local_1.value() as u16)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let __compact_action_local_2: runtime::Field = runtime::Field::from(1u128);
        let step = context.write_cell(1, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamAssertEq<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        if !(if __compact_action_local_0 {
            let __compact_value_1 = runtime::BoundedUint::<1>::new(1u128)
                .expect("Compact Uint literal fits its maximum");
            __compact_value_1
                == runtime::BoundedUint::<1>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
        } else {
            let __compact_value_2 = runtime::BoundedUint::<2>::new(2u128)
                .expect("Compact Uint literal fits its maximum");
            __compact_value_2
                == runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
        }) {
            return Err(runtime::CompactError::AssertionFailed(
                "stream ternary assert".to_owned(),
            ));
        }
        let __compact_action_local_1: runtime::Field = runtime::Field::from(1u128);
        let step = context.write_cell(1, __compact_action_local_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn streamNestedIf<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 = context.read_cell::<bool>(0)?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        let __compact_action_local_0: bool = __compact_query_0.result;
        let __compact_action_local_1: runtime::BoundedUint<4> = if __compact_action_local_0 {
            runtime::cast_unsigned::<2, 4>(if __compact_action_local_0 {
                runtime::BoundedUint::<2>::new(1u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<2>::new(2u128)
                    .expect("Compact Uint literal fits its maximum")
            })?
        } else {
            if __compact_action_local_0 {
                runtime::BoundedUint::<4>::new(3u128)
                    .expect("Compact Uint literal fits its maximum")
            } else {
                runtime::BoundedUint::<4>::new(4u128)
                    .expect("Compact Uint literal fits its maximum")
            }
        };
        let __compact_action_local_2: runtime::Field =
            runtime::Field::from((__compact_action_local_1).value());
        let step = context.write_cell(1, __compact_action_local_2)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let __compact_action_local_3: runtime::BoundedUint<65535> =
            runtime::BoundedUint::<65535>::new(1u128)
                .expect("Compact Uint literal fits its maximum");
        let step = context.increment_counter(4, __compact_action_local_3.value() as u16)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
