// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub fn hash_field(
        value: runtime::Field,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::persistent_hash(value))
    }
    pub fn commit_field(
        value: runtime::Field,
        opening: runtime::FixedBytes<32>,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::persistent_commit(value, opening))
    }
    pub fn hash_pair(
        value: runtime::FixedVector<runtime::Field, 2>,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::persistent_hash(value.clone()))
    }
    pub fn degrade_digest(
        value: runtime::FixedBytes<32>,
    ) -> Result<runtime::Field, runtime::CompactError> {
        Ok(runtime::degrade_to_transient(value))
    }
    pub fn upgrade_field(
        value: runtime::Field,
    ) -> Result<runtime::FixedBytes<32>, runtime::CompactError> {
        Ok(runtime::upgrade_from_transient(value))
    }
    pub fn degrade_hash(value: runtime::Field) -> Result<runtime::Field, runtime::CompactError> {
        Ok(runtime::degrade_to_transient(runtime::persistent_hash(
            value,
        )))
    }
}
