;;; This file is part of Compact.
;;; Copyright (C) 2026 Midnight Foundation
;;; SPDX-License-Identifier: Apache-2.0
;;; Licensed under the Apache License, Version 2.0 (the "License");
;;; you may not use this file except in compliance with the License.
;;; You may obtain a copy of the License at
;;;
;;;  	http://www.apache.org/licenses/LICENSE-2.0
;;;
;;; Unless required by applicable law or agreed to in writing, software
;;; distributed under the License is distributed on an "AS IS" BASIS,
;;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;;; See the License for the specific language governing permissions and
;;; limitations under the License.

;;; File-level scaffolding for the emitted crate.
;;;
;;; Everything that surrounds the per-circuit output: licence header, `use`
;;; lines, the `check_runtime_version!` pin, the `Witnesses` trait, and the
;;; `Contract` struct. Also indexes the natives table and owns
;;; `native-call-site-rust`, which REJECTS a native with no Rust binding
;;; rather than emitting a placeholder — four natives are deliberately
;;; unbound (see docs/rust-backend-limitations.md).
;;;
;;; See compiler/README-rust-passes.md for the module map.

      (define (header)
        ;; Full Apache-2.0 header in the form add_headers.py's --validate
        ;; gate expects. Keeps generated fixture lib.rs files passing the
        ;; repo-wide license-header CI check.
        (out "// This file is part of Compact.\n")
        (out "// Copyright (C) 2026 Midnight Foundation\n")
        (out "// SPDX-License-Identifier: Apache-2.0\n")
        (out "// Licensed under the Apache License, Version 2.0 (the \"License\");\n")
        (out "// you may not use this file except in compliance with the License.\n")
        (out "// You may obtain a copy of the License at\n")
        (out "//\n")
        (out "//  \thttp://www.apache.org/licenses/LICENSE-2.0\n")
        (out "//\n")
        (out "// Unless required by applicable law or agreed to in writing, software\n")
        (out "// distributed under the License is distributed on an \"AS IS\" BASIS,\n")
        (out "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n")
        (out "// See the License for the specific language governing permissions and\n")
        (out "// limitations under the License.\n")
        (out "\n")
        (out "// Generated by compactc. Do not edit by hand.\n")
        (out "\n")
        ;; The blanket allow set covers warnings the generated code is
        ;; expected to produce: clippy::all (style preferences don't
        ;; apply to machine-emitted code), dead_code / unused_*
        ;; (defensive emissions), and the non_*_case lints
        ;; (Compact uses snake_case for user struct / enum / field names,
        ;; which rustc would otherwise flag).
        (out "#![allow(clippy::all, dead_code, unused_imports, unused_variables, unused_parens, non_camel_case_types, non_snake_case, non_upper_case_globals)]\n")
        (out "\n")
        (out "use midnight_compact_runtime::*;\n")
        (out "use std::marker::PhantomData;\n")
        (out "\n")
        (out (format "midnight_compact_runtime::check_runtime_version!(\"~a\");\n" runtime-version-string))
        (out "\n"))

      ;; emit-witnesses: emits the per-contract Witnesses<PS> trait.
      ;; For contracts with no witness declarations (e.g. counter.compact),
      ;; also emits an `impl<PS> Witnesses<PS> for NoWitnesses {}` blanket
      ;; impl so the generated Contract<PS, W = NoWitnesses> default works
      ;; out-of-the-box.
      (define (emit-witnesses witness-decl*)
        (out "pub trait Witnesses<PS> {\n")
        (for-each
          (lambda (w)
            (nanopass-case (Ltypescript Witness-Declaration) w
              [(witness ,src ,function-name (,arg* ...) ,type)
               ;; function-name is an id record with a uniquified internal symbol
               ;; (e.g. %private$secret_key.14). Use (id-sym) to extract the
               ;; original user-facing symbol before snake-casing.
               (out (format "    fn ~a<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>"
                            (camel->snake (id-sym function-name))))
               ;; Emit each witness argument as `, name: type` after the
               ;; ctx arg. var-name is an id record — use (id-sym) before
               ;; snake-casing, matching the function-name treatment above.
               (for-each
                 (lambda (arg)
                   (nanopass-case (Ltypescript Argument) arg
                     [(,var-name ,type)
                      (out (format ", ~a: ~a"
                                   (camel->snake (id-sym var-name))
                                   (type-rust type)))]))
                 arg*)
               (out (format ") -> (PS, ~a);\n" (type-rust type)))]))
          witness-decl*)
        (out "}\n")
        (when (null? witness-decl*)
          (out "impl<PS> Witnesses<PS> for NoWitnesses {}\n"))
        (out "\n"))

      ;; emit-contract-struct: emits the public `Contract<PS, W>` struct
      ;; generic over private state type PS and a witnesses impl W
      ;; (defaulting to NoWitnesses), and opens an `impl` block containing
      ;; the `new()` constructor. The impl block is left open so that
      ;; subsequent helpers (initial_state, circuits — Tasks D4-D7) can
      ;; emit methods inside it. The caller must invoke
      ;; `close-contract-struct` after emitting those methods.
      (define (emit-contract-struct)
        (out "pub struct Contract<PS, W = NoWitnesses>\n")
        (out "where\n")
        (out "    W: Witnesses<PS>,\n")
        (out "{\n")
        (out "    pub witnesses: W,\n")
        (out "    _ps: PhantomData<PS>,\n")
        (out "}\n")
        (out "\n")
        ;; Bug-3: `PS: Clone` is required for A17's `ctx.clone()` in
        ;; helper-call shapes (drifted-ctx CircuitContext splicing).
        ;; CircuitContext<PS> derives Clone iff PS: Clone, and the
        ;; codegen emits `ctx.clone()` in several body shapes (const-
        ;; binding to impure helper after asserts, bare-call arm in
        ;; if-chain). Adding the bound here is upward-compatible —
        ;; downstream consumers that don't use Clone aren't affected.
        (out "impl<PS, W> Contract<PS, W>\n")
        (out "where\n")
        (out "    PS: Clone,\n")
        (out "    W: Witnesses<PS>,\n")
        (out "{\n")
        (out "    pub fn new(witnesses: W) -> Self {\n")
        (out "        Self { witnesses, _ps: PhantomData }\n")
        (out "    }\n"))

      ;; close-contract-struct: closes the impl block opened by
      ;; emit-contract-struct.
      (define (close-contract-struct)
        (out "}\n\n"))

      ;; witness?: returns #t if a Program-Element is a Witness-Declaration.
      (define (witness? pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(witness ,src ,function-name (,arg* ...) ,type) #t]
          [else #f]))

      ;; Collect witness declarations from a list of program elements.
      (define (program-witnesses pelt*)
        (let loop ([pelt* pelt*] [acc '()])
          (cond
            [(null? pelt*) (reverse acc)]
            [(witness? (car pelt*))
             (loop (cdr pelt*) (cons (car pelt*) acc))]
            [else (loop (cdr pelt*) acc)])))

      ;; L2 — native bindings.
      ;;
      ;; Each `(native src function-name native-entry (arg* ...) type)`
      ;; Program-Element carries a `native-entry` record (see langs.ss).
      ;; The record now has two binding fields:
      ;;   - `native-entry-function`      — the TS-side string
      ;;     (e.g. "__compactRuntime.persistentHash")
      ;;   - `native-entry-rust-function` — the Rust-side string
      ;;     (e.g. "midnight_compact_runtime::persistent_hash"), or #f if not yet
      ;;     mapped in midnight-natives.ss.
      ;;
      ;; `native-call-site-rust` extracts a usable Rust call-target from
      ;; a native Program-Element (or from any function-name id record
      ;; resolved to its native-entry by callers). When the binding hasn't
      ;; been mapped yet, returns a TODO-tagged placeholder so the
      ;; generated code makes the gap obvious. Used by I3b/J2 when
      ;; emitting call sites for native circuits.
      (define (native-pelt? pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(native ,src ,function-name ,native-entry (,arg* ...) ,type) #t]
          [else #f]))

      (define (native-pelt-entry pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(native ,src ,function-name ,native-entry (,arg* ...) ,type) native-entry]))

      (define (native-pelt-function-name pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(native ,src ,function-name ,native-entry (,arg* ...) ,type) function-name]))

      ;; build-native-id-ht: eq-hashtable from each native's function-name id
      ;; to its native-entry. Lets call-site emission look up the Rust binding
      ;; by the call's function-name id (which references the same id record
      ;; that appears in the native declaration).
      (define (build-native-id-ht pelt*)
        (let ([ht (make-eq-hashtable)])
          (for-each
            (lambda (pelt)
              (when (native-pelt? pelt)
                (eq-hashtable-set! ht
                  (native-pelt-function-name pelt)
                  (native-pelt-entry pelt))))
            pelt*)
          ht))

      (define (native-call-site-rust ne)
        (or (native-entry-rust-function ne)
            (rust-feature-error #f 'native-binding-missing
              "no Rust binding for native function ~a"
              (native-entry-function ne))))

      ;; lfield?: returns #t if a Program-Element is a Ledger-Declaration
      ;; (i.e. a `public-ledger-declaration` form). In Ltypescript the
      ;; Program-Element nonterminal includes `ldecl`, whose Ltypescript
      ;; form is `(public-ledger-declaration pl-array lconstructor)`.
      (define (lfield? pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(public-ledger-declaration ,pl-array ,lconstructor) #t]
          [else #f]))

      ;; Collect ledger field declarations from a list of program elements.
      (define (program-ledger-fields pelt*)
        (let loop ([pelt* pelt*] [acc '()])
          (cond
            [(null? pelt*) (reverse acc)]
            [(lfield? (car pelt*))
             (loop (cdr pelt*) (cons (car pelt*) acc))]
            [else (loop (cdr pelt*) acc)])))

      ;; ldecl-constructor-args: from a Program-Element of shape
      ;; (public-ledger-declaration pl-array lconstructor), extract the
      ;; constructor's Argument list. The lconstructor has shape
      ;; (constructor src (arg* ...) stmt). Returns '() if none.
      (define (ldecl-constructor-args ldecl)
        (nanopass-case (Ltypescript Program-Element) ldecl
          [(public-ledger-declaration ,pl-array ,lconstructor)
           (nanopass-case (Ltypescript Ledger-Constructor) lconstructor
             [(constructor ,src (,arg* ...) ,stmt) arg*])]
          [else '()]))

      ;; ldecl-constructor-stmt: from a Program-Element of shape
      ;; (public-ledger-declaration pl-array lconstructor), extract the
      ;; constructor's body Statement. Returns #f if none.
      (define (ldecl-constructor-stmt ldecl)
        (nanopass-case (Ltypescript Program-Element) ldecl
          [(public-ledger-declaration ,pl-array ,lconstructor)
           (nanopass-case (Ltypescript Ledger-Constructor) lconstructor
             [(constructor ,src (,arg* ...) ,stmt) stmt])]
          [else #f]))

      ;; program-constructor-args: locate the (single) public-ledger-declaration
      ;; in the Program and return its constructor's arg list. Used by
      ;; emit-initial-state to emit user-supplied constructor parameters.
      (define (program-constructor-args pelt*)
        (let ([ldecl* (program-ledger-fields pelt*)])
          (if (null? ldecl*) '() (ldecl-constructor-args (car ldecl*)))))

      ;; export-tdefn?: returns #t if a Program-Element is an
      ;; `export-typedef` form. Non-exported user enums/structs/aliases
      ;; are dropped before Ltypescript and therefore never appear here;
      ;; their values are lowered to numeric discriminants in expressions
      ;; during the language transition (see typescript-passes.ss).
      (define (export-tdefn? pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(export-typedef ,src ,type-name (,tvar-name* ...) ,type) #t]
          [else #f]))

      ;; Collect exported type definitions from a list of program elements.
      (define (program-export-tdefns pelt*)
        (let loop ([pelt* pelt*] [acc '()])
          (cond
            [(null? pelt*) (reverse acc)]
            [(export-tdefn? (car pelt*))
             (loop (cdr pelt*) (cons (car pelt*) acc))]
            [else (loop (cdr pelt*) acc)])))

      ;; circuit?: returns #t if a Program-Element is a Circuit-Definition.
      (define (circuit? pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(circuit ,src ,function-name (,arg* ...) ,type ,stmt) #t]
          [else #f]))

      ;; circuit-pelt-src: extract the src record from a Circuit-Definition
      ;; Program-Element. Used by program-circuits to distinguish
      ;; user-defined circuits from stdlib specialisations
      ;; (e.g. `some<Field>`, `none<Field>`) via `stdlib-src?`.
      (define (circuit-pelt-src pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(circuit ,src ,function-name (,arg* ...) ,type ,stmt) src]))

      ;; Collect user-defined circuit definitions from a list of program
      ;; elements. Includes both exported circuits (which become the public
      ;; Contract impl surface / `pub fn`s in `mod pure_circuits`) and
      ;; non-exported user circuits (internal helpers like
      ;; tiny.compact's `in_state` or zerocash's
      ;; `commitment_from_coin_info`). Stdlib specialisations like
      ;; `some<Field>` / `none<Field>` are excluded — they live in the
      ;; runtime as fixed Rust functions and the call-site dispatcher
      ;; rewrites references to `midnight_compact_runtime::std_lib::some` etc.
      (define (program-circuits pelt*)
        (let loop ([pelt* pelt*] [acc '()])
          (cond
            [(null? pelt*) (reverse acc)]
            [(and (circuit? (car pelt*))
                  (or (id-exported? (circuit-function-name (car pelt*)))
                      (not (stdlib-src? (circuit-pelt-src (car pelt*))))))
             (loop (cdr pelt*) (cons (car pelt*) acc))]
            [else (loop (cdr pelt*) acc)])))

      ;; circuit-function-name: extract the function-name id record from a
      ;; Circuit-Definition Program-Element. Used to query (id-pure?) at the
      ;; dispatch site without re-pattern-matching.
      (define (circuit-function-name pelt)
        (nanopass-case (Ltypescript Program-Element) pelt
          [(circuit ,src ,function-name (,arg* ...) ,type ,stmt) function-name]))

