// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use midnight_compact_runtime::*;
use std::marker::PhantomData;

midnight_compact_runtime::check_runtime_version!("0.19.101");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Pair {
    pub a: Fr,
    pub b: u8,
}
impl Aligned for Pair {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment(), &<u8 as Aligned>::alignment()])
    }
}
impl FieldRepr for Pair {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.a.field_repr(writer);
        self.b.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.a.field_size() + self.b.field_size()
    }
}
impl FromFieldRepr for Pair {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE + <u8 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let a = <Fr as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let b = <u8 as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <u8 as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <u8 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Pair { a, b })
    }
}
impl From<Pair> for midnight_compact_runtime::Value {
    fn from(s: Pair) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.a));
        _v.push(midnight_compact_runtime::Value::from(s.b));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Pair {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.a.binary_repr(writer);
        self.b.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.a.binary_len() + self.b.binary_len()
    }
}

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![new_cell(false)]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn ping(&self, ctx: CircuitContext<PS>) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(0u8))
            .push(true, new_cell(true))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn flag(&self) -> Result<bool, CompactError> {
        let qctx = QueryContext::new(
            self.state.clone(),
            midnight_compact_runtime::ContractAddress::default(),
        );
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(midnight_compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        midnight_compact_runtime::std_lib::decode_bool(av)
    }
}

pub mod pure_circuits {
    use super::*;

    pub fn as_vector(x: Fr) -> Result<[Fr; 2], CompactError> {
        Ok([x, x])
    }

    pub fn as_tuple(x: Fr) -> Result<(Fr, Fr), CompactError> {
        Ok((x, x))
    }

    pub fn hetero(x: u8) -> Result<(Fr, u16), CompactError> {
        Ok((Fr::from((x) as u64), ((x) as u16)))
    }

    pub fn one_tuple(x: Fr) -> Result<(Fr,), CompactError> {
        Ok((x,))
    }

    pub fn empty_tuple() -> Result<(), CompactError> {
        Ok(())
    }

    pub fn tuple_coerce(x: u8) -> Result<(Fr, Fr), CompactError> {
        Ok((Fr::from((x) as u64), Fr::from((x) as u64)))
    }

    pub fn tuple_var_ref(x: u8) -> Result<(Fr, Fr), CompactError> {
        let w = (Fr::from((x) as u64), Fr::from((x) as u64));
        Ok(w)
    }

    pub fn tuple_to_vector(x: Fr) -> Result<[Fr; 2], CompactError> {
        let t = (x, x);
        Ok({
            let __compact_materialize = t;
            [__compact_materialize.0, __compact_materialize.1]
        })
    }

    pub fn struct_vector_return(x: Fr) -> Result<(Pair, Pair), CompactError> {
        let v = [Pair { a: x, b: 1u8 }, Pair { a: x, b: 2u8 }];
        Ok({
            let __compact_materialize = v;
            {
                let [__compact_elt_0, __compact_elt_1] = __compact_materialize;
                (__compact_elt_0, __compact_elt_1)
            }
        })
    }

    pub fn struct_vector_to_tuple(x: Fr) -> Result<(Pair, Pair), CompactError> {
        let v = [Pair { a: x, b: 1u8 }, Pair { a: x, b: 2u8 }];
        let t = {
            let __compact_materialize = v;
            {
                let [__compact_elt_0, __compact_elt_1] = __compact_materialize;
                (__compact_elt_0, __compact_elt_1)
            }
        };
        Ok(t)
    }

    pub fn takes_vector(v: [Fr; 2]) -> Result<[Fr; 2], CompactError> {
        Ok(v)
    }

    pub fn call_vector_with_tuple(x: Fr) -> Result<[Fr; 2], CompactError> {
        let t = (x, x);
        Ok(pure_circuits::takes_vector(
            {
                let __compact_materialize = t;
                [__compact_materialize.0, __compact_materialize.1]
            }
            .clone(),
        )?)
    }

    pub fn takes_tuple(t: (Fr, Fr)) -> Result<(Fr, Fr), CompactError> {
        Ok(t)
    }

    pub fn call_tuple_with_vector(x: Fr) -> Result<(Fr, Fr), CompactError> {
        let v = [x, x];
        Ok(pure_circuits::takes_tuple(
            {
                let __compact_materialize = v;
                {
                    let [__compact_elt_0, __compact_elt_1] = __compact_materialize;
                    (__compact_elt_0, __compact_elt_1)
                }
            }
            .clone(),
        )?)
    }

    pub fn takes_pair_vector(v: [Pair; 2]) -> Result<[Pair; 2], CompactError> {
        Ok(v)
    }

    pub fn call_pair_vector_with_tuple(x: Fr) -> Result<[Pair; 2], CompactError> {
        let t = (Pair { a: x, b: 1u8 }, Pair { a: x, b: 2u8 });
        Ok(pure_circuits::takes_pair_vector(
            {
                let __compact_materialize = t;
                [__compact_materialize.0, __compact_materialize.1]
            }
            .clone(),
        )?)
    }
}
