// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct MerkleTreeDigest {
        pub field: runtime::Field,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 38);
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const t: runtime::slots::MerkleSlot<runtime::BoundedUint<255>, 3u8, false> =
        runtime::slots::MerkleSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 38);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Inspect this declared plain Merkle tree in the borrowed public state.
        pub fn t(
            &self,
        ) -> Result<
            runtime::slots::PlainMerkleStateView<'a, runtime::BoundedUint<255>, 3u8, D>,
            runtime::CompactError,
        > {
            crate::ledger_slots::t.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state =
            runtime::ledger::contract_state(vec![runtime::ledger::constructor_merkle_tree(3u8)]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn append<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.insert(context, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
        __compact_param_1: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step =
            crate::ledger_slots::t.insert_index(context, __compact_param_0, __compact_param_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn append_hash<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedBytes<32>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.insert_hash(context, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place_hash<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedBytes<32>,
        __compact_param_1: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.insert_hash_index(
            context,
            __compact_param_0,
            __compact_param_1,
        )?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place_default<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.insert_index_default(context, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn reset_tree<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::t.reset_to_default(context)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn full<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = crate::ledger_slots::t.is_full(context)?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn known<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: crate::types::MerkleTreeDigest,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = crate::ledger_slots::t.check_root(context, __compact_param_0.clone())?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn append<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_insert(frame, __compact_param_0)?;
            Ok(frame.finish(()))
        }
        pub fn place<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
            __compact_param_1: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_insert_index(
                frame,
                __compact_param_0,
                __compact_param_1,
            )?;
            Ok(frame.finish(()))
        }
        pub fn append_hash<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::FixedBytes<32>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_insert_hash(frame, __compact_param_0)?;
            Ok(frame.finish(()))
        }
        pub fn place_hash<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::FixedBytes<32>,
            __compact_param_1: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_insert_hash_index(
                frame,
                __compact_param_0,
                __compact_param_1,
            )?;
            Ok(frame.finish(()))
        }
        pub fn place_default<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame =
                crate::ledger_slots::t.record_insert_index_default(frame, __compact_param_0)?;
            Ok(frame.finish(()))
        }
        pub fn reset_tree<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::t.record_reset_to_default(frame)?;
            Ok(frame.finish(()))
        }
        pub fn full<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, bool>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let (frame, observed): (_, bool) = crate::ledger_slots::t.record_is_full(frame)?;
            Ok(frame.finish(observed))
        }
        pub fn known<Private>(
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: crate::types::MerkleTreeDigest,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, bool>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let (frame, observed): (_, bool) =
                crate::ledger_slots::t.record_check_root(frame, (__compact_param_0).clone())?;
            Ok(frame.finish(observed))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn append<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                value: runtime::BoundedUint<255>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::append(context, value)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn append_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                value: runtime::BoundedUint<255>,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(value);
                let recorded = self.append(observed.circuit_context(private_state), value)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "append", input,
                ))
            }
            pub fn place<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                value: runtime::BoundedUint<255>,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::place(context, value, index)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn place_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                value: runtime::BoundedUint<255>,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from((value, index));
                let recorded = self.place(observed.circuit_context(private_state), value, index)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "place", input,
                ))
            }
            pub fn append_hash<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                hash: runtime::FixedBytes<32>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::append_hash(context, hash)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn append_hash_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                hash: runtime::FixedBytes<32>,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(hash);
                let recorded = self.append_hash(observed.circuit_context(private_state), hash)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "append_hash",
                    input,
                ))
            }
            pub fn place_hash<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                hash: runtime::FixedBytes<32>,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::place_hash(context, hash, index)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn place_hash_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                hash: runtime::FixedBytes<32>,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from((hash, index));
                let recorded =
                    self.place_hash(observed.circuit_context(private_state), hash, index)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "place_hash",
                    input,
                ))
            }
            pub fn place_default<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::place_default(context, index)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn place_default_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                index: runtime::BoundedUint<18446744073709551615>,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(index);
                let recorded =
                    self.place_default(observed.circuit_context(private_state), index)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "place_default",
                    input,
                ))
            }
            pub fn reset_tree<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::reset_tree(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn reset_tree_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded = self.reset_tree(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed,
                    recorded,
                    "reset_tree",
                    input,
                ))
            }
            pub fn full<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<
                runtime::recording::RecordedCircuitResult<Private, bool>,
                runtime::CompactError,
            > {
                crate::ledger_contract::recorded::full(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn full_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, bool>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded = self.full(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "full", input,
                ))
            }
            pub fn known<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
                root: crate::types::MerkleTreeDigest,
            ) -> Result<
                runtime::recording::RecordedCircuitResult<Private, bool>,
                runtime::CompactError,
            > {
                crate::ledger_contract::recorded::known(context, root)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn known_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
                root: crate::types::MerkleTreeDigest,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, bool>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from((root).clone());
                let recorded = self.known(observed.circuit_context(private_state), root)?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "known", input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn append<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            value: runtime::BoundedUint<255>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append(context, value)
        }
        pub fn place<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            value: runtime::BoundedUint<255>,
            index: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::place(context, value, index)
        }
        pub fn append_hash<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            hash: runtime::FixedBytes<32>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append_hash(context, hash)
        }
        pub fn place_hash<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            hash: runtime::FixedBytes<32>,
            index: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::place_hash(context, hash, index)
        }
        pub fn place_default<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            index: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::place_default(context, index)
        }
        pub fn reset_tree<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::reset_tree(context)
        }
        pub fn full<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
            crate::ledger_contract::full(context)
        }
        pub fn known<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            root: crate::types::MerkleTreeDigest,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
            crate::ledger_contract::known(context, root)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
