// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    #[derive(
        ::core::clone::Clone,
        ::core::fmt::Debug,
        ::core::default::Default,
        ::core::cmp::PartialEq,
        ::core::cmp::Eq,
        ::midnight_compact_runtime::CompactCellValue,
        ::midnight_compact_runtime::CompactStructRepr,
    )]
    pub struct Pair {
        pub a: ::midnight_compact_runtime::Field,
        pub b: ::midnight_compact_runtime::BoundedUint<255>,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 50);
    pub fn as_vector(
        x: runtime::Field,
    ) -> Result<runtime::FixedVector<runtime::Field, 2>, runtime::CompactError> {
        Ok(runtime::FixedVector::new([x, x]))
    }
    pub fn as_tuple(
        x: runtime::Field,
    ) -> Result<(runtime::Field, runtime::Field), runtime::CompactError> {
        Ok((x, x))
    }
    pub fn hetero(
        x: runtime::BoundedUint<255>,
    ) -> Result<(runtime::Field, runtime::BoundedUint<65535>), runtime::CompactError> {
        Ok((
            runtime::Field::from((x).value()),
            runtime::cast_unsigned::<255, 65535>(x)?,
        ))
    }
    pub fn one_tuple(x: runtime::Field) -> Result<(runtime::Field,), runtime::CompactError> {
        Ok((x,))
    }
    pub fn empty_tuple() -> Result<(), runtime::CompactError> {
        Ok(())
    }
    pub fn tuple_coerce(
        x: runtime::BoundedUint<255>,
    ) -> Result<(runtime::Field, runtime::Field), runtime::CompactError> {
        Ok((
            runtime::Field::from((x).value()),
            runtime::Field::from((x).value()),
        ))
    }
    pub fn tuple_var_ref(
        x: runtime::BoundedUint<255>,
    ) -> Result<(runtime::Field, runtime::Field), runtime::CompactError> {
        Ok({
            let __compact_local_w: (runtime::BoundedUint<255>, runtime::BoundedUint<255>) = (x, x);
            {
                let __compact_cast_source_0 = __compact_local_w;
                let (__compact_cast_item_0_0, __compact_cast_item_0_1) = __compact_cast_source_0;
                (
                    runtime::Field::from((__compact_cast_item_0_0).value()),
                    runtime::Field::from((__compact_cast_item_0_1).value()),
                )
            }
        })
    }
    pub fn tuple_to_vector(
        x: runtime::Field,
    ) -> Result<runtime::FixedVector<runtime::Field, 2>, runtime::CompactError> {
        Ok({
            let __compact_local_t: (runtime::Field, runtime::Field) = (x, x);
            {
                let __compact_cast_source_0 = __compact_local_t;
                let (__compact_cast_item_0_0, __compact_cast_item_0_1) = __compact_cast_source_0;
                runtime::FixedVector::new([__compact_cast_item_0_0, __compact_cast_item_0_1])
            }
        })
    }
    pub fn struct_vector_return(
        x: runtime::Field,
    ) -> Result<(crate::types::Pair, crate::types::Pair), runtime::CompactError> {
        Ok({
            let __compact_local_v: runtime::FixedVector<crate::types::Pair, 2> =
                runtime::FixedVector::new([
                    crate::types::Pair {
                        a: x,
                        b: runtime::BoundedUint::<255>::new(1u128)
                            .expect("Compact Uint literal fits its maximum"),
                    },
                    crate::types::Pair {
                        a: x,
                        b: runtime::BoundedUint::<255>::new(2u128)
                            .expect("Compact Uint literal fits its maximum"),
                    },
                ]);
            {
                let __compact_cast_source_0 = __compact_local_v.clone();
                let [__compact_cast_item_0_0, __compact_cast_item_0_1] =
                    __compact_cast_source_0.into_array();
                (__compact_cast_item_0_0, __compact_cast_item_0_1)
            }
        })
    }
    pub fn struct_vector_to_tuple(
        x: runtime::Field,
    ) -> Result<(crate::types::Pair, crate::types::Pair), runtime::CompactError> {
        Ok({
            let __compact_local_v: runtime::FixedVector<crate::types::Pair, 2> =
                runtime::FixedVector::new([
                    crate::types::Pair {
                        a: x,
                        b: runtime::BoundedUint::<255>::new(1u128)
                            .expect("Compact Uint literal fits its maximum"),
                    },
                    crate::types::Pair {
                        a: x,
                        b: runtime::BoundedUint::<255>::new(2u128)
                            .expect("Compact Uint literal fits its maximum"),
                    },
                ]);
            {
                let __compact_local_t: (crate::types::Pair, crate::types::Pair) = {
                    let __compact_cast_source_0 = __compact_local_v.clone();
                    let [__compact_cast_item_0_0, __compact_cast_item_0_1] =
                        __compact_cast_source_0.into_array();
                    (__compact_cast_item_0_0, __compact_cast_item_0_1)
                };
                __compact_local_t.clone()
            }
        })
    }
}
/// Typed descriptors for Compact ledger declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const flag: runtime::slots::CellSlot<bool> = runtime::slots::CellSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 50);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    /// Read-only projection of an existing ledger-8 public state.
    pub struct PublicStateView<'a, D: runtime::ledger::DB = runtime::ledger::DefaultDB> {
        state: &'a runtime::ledger::StateValue<D>,
    }
    impl<'a, D: runtime::ledger::DB> PublicStateView<'a, D> {
        /// Decode this declared Cell from the borrowed public state.
        pub fn flag(&self) -> Result<bool, runtime::CompactError> {
            crate::ledger_slots::flag.inspect(self.state)
        }
    }
    impl<'a, S: runtime::public_state::PublicStateSource> From<&'a S>
        for PublicStateView<'a, S::Database>
    {
        fn from(source: &'a S) -> Self {
            Self {
                state: source.public_state(),
            }
        }
    }
    /// Implement for infallible callbacks; use TryWitnesses for fallible ledger reads.
    #[runtime::compact_witness_bridge]
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_cell::<
            bool,
            runtime::ledger::DefaultDB,
        >(Default::default())]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn ping<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let frame = runtime::context::CircuitFrame::new(context);
        let (frame, ()) = frame.apply(|context| crate::ledger_slots::flag.write(context, true))?;
        Ok(frame.finish(()))
    }
    /// Circuits with a replayable ordered ledger program.
    pub mod recorded {
        use midnight_compact_runtime as runtime;
        pub fn ping<Private>(
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
        {
            let frame = runtime::recording::RecordingFrame::new(context);
            let frame = crate::ledger_slots::flag.record_write(frame, true)?;
            Ok(frame.finish(()))
        }
        /// Typed handle for circuits with a complete recorded trace.
        pub struct Contract;
        impl Contract {
            pub fn ping<Private>(
                &self,
                context: runtime::context::CircuitContext<Private>,
            ) -> Result<runtime::recording::RecordedCircuitResult<Private, ()>, runtime::CompactError>
            {
                crate::ledger_contract::recorded::ping(context)
            }
            #[cfg(feature = "ledger-transaction")]
            pub fn ping_call<'observed, Private>(
                &self,
                observed: &'observed runtime::transaction::ObservedContractState,
                private_state: Private,
            ) -> Result<
                runtime::transaction::RecordedCall<'observed, Private, ()>,
                runtime::CompactError,
            > {
                let input = runtime::fab::AlignedValue::from(());
                let recorded = self.ping(observed.circuit_context(private_state))?;
                Ok(runtime::transaction::RecordedCall::new(
                    observed, recorded, "ping", input,
                ))
            }
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
        pub recording: recorded::Contract,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self {
                witnesses,
                recording: recorded::Contract,
            }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self {
                witnesses: (),
                recording: recorded::Contract,
            }
        }
    }
    impl<W> Contract<W> {
        pub fn ping<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::ping(context)
        }
        /// Access replayable circuit calls for this contract.
        pub fn recording(&self) -> &recorded::Contract {
            &self.recording
        }
    }
}
