// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 4);
    pub fn less(
        left: runtime::BoundedUint<65535>,
        right: runtime::BoundedUint<65535>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(left.value() < right.value())
    }
    pub fn less_equal(
        left: runtime::BoundedUint<65535>,
        right: runtime::BoundedUint<65535>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(left.value() <= right.value())
    }
    pub fn greater(
        left: runtime::BoundedUint<65535>,
        right: runtime::BoundedUint<65535>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(left.value() > right.value())
    }
    pub fn greater_equal(
        left: runtime::BoundedUint<65535>,
        right: runtime::BoundedUint<65535>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(left.value() >= right.value())
    }
    pub fn mixed_width(
        left: runtime::BoundedUint<255>,
        right: runtime::BoundedUint<65535>,
    ) -> Result<bool, runtime::CompactError> {
        Ok(runtime::cast_unsigned::<255, 65535>(left)?.value() < right.value())
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 4);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {
        fn echo(
            &self,
            context: runtime::context::WitnessContext<'_, Private, LedgerView<'_>>,
            __compact_param_0: runtime::BoundedUint<65535>,
        ) -> (Private, runtime::BoundedUint<65535>);
    }
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn witnessed_less<Private, W: Witnesses<Private>>(
        context: runtime::context::CircuitContext<Private>,
        witnesses: &W,
        __compact_param_0: runtime::BoundedUint<65535>,
        __compact_param_1: runtime::BoundedUint<65535>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let total_cost = runtime::context::RunningCost::default();
        let mut private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_argument_0 = __compact_param_0;
        let (__compact_next_private_1, __compact_witness_1) = witnesses.echo(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_0,
        );
        context.private_state = __compact_next_private_1;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_1.clone(),
        ));
        let __compact_expression_local_2: runtime::BoundedUint<65535> = __compact_witness_1;
        let __compact_value_3 = __compact_expression_local_2;
        let __compact_argument_4 = __compact_param_1;
        let (__compact_next_private_5, __compact_witness_5) = witnesses.echo(
            context.witness_context_with(LedgerView {
                state: context.query.state.get_ref(),
            }),
            __compact_argument_4,
        );
        context.private_state = __compact_next_private_5;
        private_transcript_outputs.push(runtime::fab::AlignedValue::from(
            __compact_witness_5.clone(),
        ));
        let result = __compact_value_3.value() < __compact_witness_5.value();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {
        pub fn witnessed_less<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<65535>,
            __compact_param_1: runtime::BoundedUint<65535>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError>
        where
            W: Witnesses<Private>,
        {
            crate::ledger_contract::witnessed_less(
                context,
                &self.witnesses,
                __compact_param_0,
                __compact_param_1,
            )
        }
    }
}
