// Generated by compactc. Do not edit.

pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct MerkleTreeDigest {
        pub field: runtime::Field,
    }
}
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_historic_merkle_tree(3u8),
        ]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn append<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert(0, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
        __compact_param_1: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert_index(0, __compact_param_0, __compact_param_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn forget_history<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_reset_history(0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn full<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = context.historic_is_full(0, 3)?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn known<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: crate::types::MerkleTreeDigest,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = context.historic_check_root(0, __compact_param_0.clone())?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
