// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod types {
    use midnight_compact_runtime as runtime;
    use runtime::{BinaryHashRepr, CompactCellValue, FieldRepr, Fr, FromFieldRepr, MemWrite};
    #[derive(
        Clone,
        Debug,
        Default,
        PartialEq,
        Eq,
        CompactCellValue,
        BinaryHashRepr,
        FieldRepr,
        FromFieldRepr,
    )]
    pub struct MerkleTreeDigest {
        pub field: runtime::Field,
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 6);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 6);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
        #[allow(dead_code)]
        meter: &'a runtime::context::WitnessReadMeter<'a>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_historic_merkle_tree(3u8),
        ]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn append<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert(0, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::BoundedUint<255>,
        __compact_param_1: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert_index(0, __compact_param_0, __compact_param_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn append_hash<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedBytes<32>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert_hash(0, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn place_hash<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedBytes<32>,
        __compact_param_1: runtime::BoundedUint<18446744073709551615>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_insert_hash_index(0, __compact_param_0, __compact_param_1)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn forget_history<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_reset_history(0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn reset_tree<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.historic_reset_to_default(0, 3)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn full<Private>(
        context: runtime::context::CircuitContext<Private>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = context.historic_is_full(0, 3)?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn known<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: crate::types::MerkleTreeDigest,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let read_step = context.historic_check_root(0, __compact_param_0.clone())?;
        let context = read_step.context;
        total_cost += read_step.gas_cost;
        let result = read_step.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {
        pub fn append<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append(context, __compact_param_0)
        }
        pub fn place<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::BoundedUint<255>,
            __compact_param_1: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::place(context, __compact_param_0, __compact_param_1)
        }
        pub fn append_hash<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::FixedBytes<32>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::append_hash(context, __compact_param_0)
        }
        pub fn place_hash<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::FixedBytes<32>,
            __compact_param_1: runtime::BoundedUint<18446744073709551615>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::place_hash(context, __compact_param_0, __compact_param_1)
        }
        pub fn forget_history<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::forget_history(context)
        }
        pub fn reset_tree<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::reset_tree(context)
        }
        pub fn full<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
            crate::ledger_contract::full(context)
        }
        pub fn known<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: crate::types::MerkleTreeDigest,
        ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
            crate::ledger_contract::known(context, __compact_param_0)
        }
    }
}
