// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub fn ping(b: bool) -> Result<bool, runtime::CompactError> {
        Ok(b)
    }
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<
                runtime::BoundedUint<18446744073709551615>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<bool, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
        ]);
        {
            let mut context = runtime::context::ConstructorResult::new(__compact_context, state)
                .into_circuit_context(runtime::ledger::ContractAddress::default());
            let mut total_cost = runtime::context::RunningCost::default();
            let __compact_constructor_local_0: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(7u128)
                    .expect("Compact Uint literal fits its maximum");
            let step =
                context.write_cell_at_path(&[0, 0], (__compact_constructor_local_0).clone())?;
            context = step.context;
            let __compact_constructor_local_1: runtime::BoundedUint<18446744073709551615> =
                runtime::BoundedUint::<18446744073709551615>::new(42u128)
                    .expect("Compact Uint literal fits its maximum");
            let step =
                context.write_cell_at_path(&[1, 13], (__compact_constructor_local_1).clone())?;
            context = step.context;
            let step = context.write_cell_at_path(&[1, 14], (true).clone())?;
            context = step.context;
            let _ = total_cost;
            Ok(context.into_constructor_result())
        }
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {}
}
