// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
}
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![
            runtime::ledger::constructor_cell::<
                runtime::FixedVector<runtime::Field, 2>,
                runtime::ledger::DefaultDB,
            >(Default::default()),
            runtime::ledger::constructor_cell::<runtime::FixedBytes<32>, runtime::ledger::DefaultDB>(
                Default::default(),
            ),
        ]);
        {
            let mut context = runtime::context::ConstructorResult::new(__compact_context, state)
                .into_circuit_context(runtime::ledger::ContractAddress::default());
            let mut total_cost = runtime::context::RunningCost::default();
            let __compact_constructor_local_0: runtime::FixedVector<runtime::Field, 2> =
                runtime::FixedVector::new([
                    runtime::Field::from(0u128),
                    runtime::Field::from(0u128),
                ]);
            let step = context.write_cell(0, (__compact_constructor_local_0.clone()).clone())?;
            context = step.context;
            let __compact_constructor_local_1: runtime::FixedBytes<32> =
                runtime::persistent_hash(runtime::FixedVector::new([
                    runtime::Field::from(0u128),
                    runtime::Field::from(0u128),
                ]));
            let step = context.write_cell(1, (__compact_constructor_local_1).clone())?;
            context = step.context;
            let _ = total_cost;
            Ok(context.into_constructor_result())
        }
    }
    pub(crate) fn scalarHelper<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_value_0 = runtime::persistent_hash(__compact_param_0);
        let __compact_query_1 = context.read_cell::<runtime::FixedBytes<32>>(1)?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        let result = __compact_value_0 == __compact_query_1.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub(crate) fn aggHelper<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedVector<runtime::Field, 4>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_value_0 = runtime::persistent_hash(__compact_param_0.clone());
        let __compact_query_1 = context.read_cell::<runtime::FixedBytes<32>>(1)?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        let result = __compact_value_0 == __compact_query_1.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub(crate) fn noCollisionHelper<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedVector<runtime::Field, 2>,
    ) -> Result<runtime::context::CircuitResult<Private, bool>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_value_0 = runtime::persistent_hash(__compact_param_0.clone());
        let __compact_query_1 = context.read_cell::<runtime::FixedBytes<32>>(1)?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        let result = __compact_value_0 == __compact_query_1.result;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn setHash<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedBytes<32>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = context.write_cell(1, __compact_param_0)?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn checkScalarScope<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedVector<runtime::Field, 2>,
        __compact_param_1: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_call_argument_0 = __compact_param_1;
        let __compact_call_1 = scalarHelper(context, __compact_call_argument_0)?;
        context = __compact_call_1.context;
        total_cost += __compact_call_1.gas_cost;
        if !(__compact_call_1.result) {
            return Err(runtime::CompactError::AssertionFailed(
                "scalar helper formal took the caller's vector type".to_owned(),
            ));
        }
        let step = context.write_cell(0, __compact_param_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn checkAggScope<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedVector<runtime::Field, 2>,
        __compact_param_1: runtime::FixedVector<runtime::Field, 4>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_call_argument_0 = __compact_param_1.clone();
        let __compact_call_1 = aggHelper(context, __compact_call_argument_0)?;
        context = __compact_call_1.context;
        total_cost += __compact_call_1.gas_cost;
        if !(__compact_call_1.result) {
            return Err(runtime::CompactError::AssertionFailed(
                "aggregate helper formal took the caller's shorter vector type".to_owned(),
            ));
        }
        let step = context.write_cell(0, __compact_param_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn checkNoCollisionScope<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::FixedVector<runtime::Field, 2>,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_call_argument_0 = __compact_param_0.clone();
        let __compact_call_1 = noCollisionHelper(context, __compact_call_argument_0)?;
        context = __compact_call_1.context;
        total_cost += __compact_call_1.gas_cost;
        if !(__compact_call_1.result) {
            return Err(runtime::CompactError::AssertionFailed(
                "aggregate helper formal was not recovered".to_owned(),
            ));
        }
        let step = context.write_cell(0, __compact_param_0.clone())?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
}
