// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit.

/// The matching Midnight Compact Rust runtime used by this generated crate.
pub use midnight_compact_runtime as runtime;
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
}
/// Typed descriptors for Compact Cell, Counter, Set, Map, and List declarations.
#[allow(non_upper_case_globals)]
pub mod ledger_slots {
    use midnight_compact_runtime as runtime;
    pub const entries: runtime::slots::MapSlot<runtime::OpaqueString, runtime::Field> =
        runtime::slots::MapSlot::new(&[0u8]);
}
#[allow(non_snake_case, non_camel_case_types, unused_mut, unused_variables)]
pub mod ledger_contract {
    use midnight_compact_runtime as runtime;
    const _: () = assert!(runtime::RUST_RUNTIME_ABI == 3);
    pub struct LedgerView<'a> {
        #[allow(dead_code)]
        state: &'a runtime::ledger::StateValue<runtime::ledger::DefaultDB>,
    }
    impl<'a> LedgerView<'a> {}
    pub trait Witnesses<Private> {}
    pub fn initial_state<Private>(
        __compact_context: runtime::context::ConstructorContext<Private>,
    ) -> Result<runtime::context::ConstructorResult<Private>, runtime::CompactError> {
        let state = runtime::ledger::contract_state(vec![runtime::ledger::constructor_map()]);
        Ok(runtime::context::ConstructorResult::new(
            __compact_context,
            state,
        ))
    }
    pub fn put<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::OpaqueString,
        __compact_param_1: runtime::Field,
    ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let step = crate::ledger_slots::entries.insert(
            context,
            __compact_param_0.clone(),
            __compact_param_1,
        )?;
        let context = step.context;
        total_cost += step.gas_cost;
        let result = ();
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    pub fn ensure<Private>(
        context: runtime::context::CircuitContext<Private>,
        __compact_param_0: runtime::OpaqueString,
    ) -> Result<runtime::context::CircuitResult<Private, runtime::Field>, runtime::CompactError>
    {
        let mut total_cost = runtime::context::RunningCost::default();
        let private_transcript_outputs = Vec::new();
        let mut context = context;
        let __compact_query_0 =
            crate::ledger_slots::entries.member(context, (__compact_param_0.clone()).clone())?;
        context = __compact_query_0.context;
        total_cost += __compact_query_0.gas_cost;
        if !(__compact_query_0.result) {
            return Err(runtime::CompactError::AssertionFailed(
                "missing key".to_owned(),
            ));
        }
        let mut context = context;
        let __compact_query_1 =
            crate::ledger_slots::entries.lookup(context, (__compact_param_0.clone()).clone())?;
        context = __compact_query_1.context;
        total_cost += __compact_query_1.gas_cost;
        let __compact_expression_local_2: runtime::Field = __compact_query_1.result;
        let result = __compact_expression_local_2;
        Ok(runtime::context::CircuitResult {
            context,
            result,
            gas_cost: total_cost,
            private_transcript_outputs,
        })
    }
    /// Groups the contract's exported circuits for Rust consumers.
    pub struct Contract<W> {
        #[allow(dead_code)]
        witnesses: W,
    }
    impl<W> From<W> for Contract<W> {
        fn from(witnesses: W) -> Self {
            Self { witnesses }
        }
    }
    impl Default for Contract<()> {
        fn default() -> Self {
            Self { witnesses: () }
        }
    }
    impl<W> Contract<W> {
        pub fn put<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::OpaqueString,
            __compact_param_1: runtime::Field,
        ) -> Result<runtime::context::CircuitResult<Private, ()>, runtime::CompactError> {
            crate::ledger_contract::put(context, __compact_param_0, __compact_param_1)
        }
        pub fn ensure<Private>(
            &self,
            context: runtime::context::CircuitContext<Private>,
            __compact_param_0: runtime::OpaqueString,
        ) -> Result<runtime::context::CircuitResult<Private, runtime::Field>, runtime::CompactError>
        {
            crate::ledger_contract::ensure(context, __compact_param_0)
        }
    }
}
