// Generated by compactc. Do not edit.

pub mod pure_circuits {
    use midnight_compact_runtime as runtime;
    pub fn identity(value: runtime::Field) -> Result<runtime::Field, runtime::CompactError> {
        Ok(value)
    }
}
